### ISSUE TITLE
Jacking a Vehicle with 2 fire modes can cause the ammo types to be swapped

### ISSUE THREAD

**Issue by Dethdeath** [psforever/PSF-LoginServer#1001]
https://streamable.com/o7wy7k
First half of the video isn't as interesting, but I wanted to include it to show the entire process.

At 1:21 you see the ammo count showing 1/40 for the flak cannon after being jacked despite being at 0/40 before being jacked, which might be the first sign of things breaking.
After that it just gets worse and then the ammo types get swapped.

Reaver:
![RocketPods](https://user-images.githubusercontent.com/77748540/172035080-5d308c50-4a1f-4a72-bb9a-43cbeca8394d.png)

**Comment by Fate-JH** [comment]
It's not possible to construct a weapon with 0/x of any type with just the packet for object creation.  Occasionally, I have to remake the weapon and you'll always have that one bullet.  I call the "fire stop" routine which sends the packet to ensure the user stops does continue shooting if they end up in a state where the client allows them to shoot but the server says their magazine should be empty.  That's the origin of that one last shot being visible to everyone.  It should completely bypass projectile generation server side, thus do no harm.

Reloading 40 at a time seems like either an ammunition indexing issue, or a fire mode mismatch.
