### ISSUE TITLE
Terminal condition glitched at NC base, Ikanam

### ISSUE THREAD

**Issue by ReDuzed** [psforever/PSF-LoginServer#1017]
Time of: *Monday, 5:49 PM CET*
In-game Location: *Ikanam / Amerish*
Factions: *Character is TR, base is NC*
<hr>

Upon REK engaging the vehicle terminal, the timer does not appear to start and the message is simply "Access Terminal." 

<a href="https://cdn.discordapp.com/attachments/295670273544290304/1069765184907911188/vehtermbugged.mp4">6 second video clip</a>

**Comment by ReDuzed** [comment]
Upon further consideration this may have been a glitch that occasionally happened in live due to a trade of hands, gen conditions, terminal destroying, and base flips the likes of which happened to this base earlier.

**Comment by Fate-JH** [comment]
If it's a "(Gemini) Live" glitch, it's potentially a client bug that's legacy.  All that can be done is try to align the server in a way that the conditions of the issue on the client(s) are infrequent.  Can you elaborate on the glitch?
