### ISSUE TITLE
Boomer causes crash when zoning

### ISSUE THREAD

**Issue by ScrawnyRonnie** [psforever/PSF-LoginServer#1020]
The act of laying a Boomer (Remote-Detonated Charge) will cause your client to crash if you then zone to another cont via Warpgate, recall, or quit the game (using quit from menu). The reproduction steps are rather simple:

1) Go anywhere (besides Sanc for obvious reasons) and lay a Boomer down.
2) Detonate it (or don't)
3) Recall, quit, or go through a Warpgate
4) Crash :)

I tested quite a few scenarios to see if only specific thing cause the crash, but they all had the same result. Some other things tested:
- Just laying the boomer and holding the trigger, too indecisive to make it go boom
- Dropping the trigger
- Destroying the trigger
- Dropping the trigger, picking it up with another friendly, and detonating it
- Putting the trigger into the abyss (a Locker, which Dethdeath found it just disappears)
- Destroying the boomer via another empire

Your destiny is pretty much sealed. The only escape I found was to Alt F4, which funny enough I still had the trigger when I logged back in and was able to detonate it and successfully recall, so there is that... Is there also an amount of time that could pass that would make this not happen? Maybe, but that is something I didn't try.

Also, laying other types of CE did not cause this. Appears to be unique to the boomer. I don't use them often so I've no idea how long this has been around.

**Comment by Fate-JH** [comment]
So it does.
Oh dear.

Oh dear.

**Comment by Fate-JH** [comment]
I disabled the boomer trigger from spawning and the crash remains, though it mutates into stalling dead onto the deployment map.  Even my `!suicide` hack doesn't resolve respawning.
