### ISSUE TITLE
Decimator only has 2 rockets

### ISSUE THREAD

**Issue by ScrawnyRonnie** [psforever/PSF-LoginServer#1026]
When firing a Deci, the 2nd shot will result in it being discarded. It will briefly show 1 rocket remaining, but then disappears. Unfortunately the 2nd rocket doesn't do twice the damage, still giving you a feeling of having all 3 shots.

Looting a Deci that has been shot 1 time shows only 1 remaining rocket when you equip it as well.

**Comment by Dethdeath** [comment]
In alt fire mode (missile cam), you do get the 3 shots.

**Comment by ScrawnyRonnie** [comment]
& this is why multiple people testing is better. I didn't think to try that!
