### ISSUE TITLE
HotSpots Not Going Away

### ISSUE THREAD

**Issue by xUNTOUCHABLEx** [psforever/PSF-LoginServer#1032]
Hotspots on continent Amerish are not going away after they appear on the map. Specific at base Ikanam.

**Comment by ScrawnyRonnie** [comment]
Diamonds aren't the only things that last forever.
![image](https://user-images.githubusercontent.com/73139382/219908800-e6e983f2-35b0-4d87-8648-8bf4946a113a.png)

It seemed like it was only Amerish doing this, but I happened upon another reason they stick around.
1) Shoot a turret at a neutral base or tower. It won't create a hotspot (yet)
2) Shoot a turret at an enemy base
3) Look at your map and you will now see hotspots at the enemy and neutral base
4) Any hotspots created from then on stays on that zone forever

It's as if we're looking at an overlay of every fight at every base ever. It's quite a beautiful sight.
