### ISSUE TITLE
Galaxy - Galaxy passengers crash when pilot bails out

### ISSUE THREAD

**Issue by Dethdeath** [psforever/PSF-LoginServer#1035]
When the pilot of a galaxy bails out, the passenger's client essentially crashes, they are in a frozen state with no weapons or the ability to use chat or move the camera.
During our test we went through a WG several times, but this doesn't seem required to reproduce it.

**Comment by Fate-JH** [comment]
Just to confirm, you're not using "no `/helmet` cosmetic" characters for these tests, are you?

**Comment by ScrawnyRonnie** [comment]
After what I went through on the test server with cosmetics I thought that could have something to do with the inconsistent results we have while testing. For example, while zoning a lot I never had an issue with a passenger or pilot on my own as far as crashing or a desync. When untouchable joined me as a passenger I started having issues. His char was the only one at/above br 24

**Comment by Fate-JH** [comment]
Untouchable, living up to his name.
I guess correcting the default state of cosmetics upon BR24 is where I should aim next.
After that, testing and confirmation in this matter may resume.

**Comment by Dethdeath** [comment]
Passenger perspective:

https://user-images.githubusercontent.com/77748540/221231171-33e15493-cbc0-45a1-9949-781b4e7ccde8.mp4


Both of these characters are BR15.

**Comment by ScrawnyRonnie** [comment]
Weird... every time I bailed the passengers never did that. This was with pulling one from sanc and zoning somewhere or pulling one from another cont and bailing there too.

**Comment by ScrawnyRonnie** [comment]
I did this one again and have the same results as Deth now. Only way out is to Alt F4 on the passenger's clients. It is Galaxy specific. I tested bailing as the pilot from a GG, Phant, and Lib and passengers/gunners all ejected with the pilot. It also did not matter if I zoned with everyone in it first or not.
