### ISSUE TITLE
Galaxy - Lodestar - Vehicle gets stuck in the back after zoning

### ISSUE THREAD

**Issue by Dethdeath** [psforever/PSF-LoginServer#1036]
When you load a vehicle in the back of a galaxy or a lodestar, it cannot get out on another continent once you go through a warpgate. Kicking the vehicle out doesn't work.
Deconstructing the galaxy or lodestar does let the vehicle out.

**Comment by ScrawnyRonnie** [comment]
Confirmed you cannot kick the vehicle or bail as the cargo vehicle driver.

Related note that Deth mentioned in Discord, if you pull a Gal/Lode somewhere other than Sanc and load a cargo vehicle, the driver of the vehicle and any passengers will experience a 'Connection Problem' window and have to exit the game. I tested it several times with the same result. Fine in Sanc; issue on other conts.

**Comment by Fate-JH** [comment]
Fixed by #1060
