### ISSUE TITLE
Players can get killed while deconstructing their avatar

### ISSUE THREAD

**Issue by Dethdeath** [psforever/PSF-LoginServer#1037]
Spawn tube or AMS doesn't make a difference.
The player avatar should either be invulnerable or disappear instantly.

**Comment by Fate-JH** [comment]
Before anything else, the player must exist in the game world until that player character can complete their reconstruction process, or can cancel it.  If no one is recognized as the avatar at any point until it is safe, the client will lock.  The only time this doesn't have to be the case is if a full zone change starts - the player character may stop existing on the old zone at almost any point.

**Comment by Dethdeath** [comment]
So then the "solution" here would be to make the player avatar invulnerable while they are looking at the map/respawn timer?
