### ISSUE TITLE
The 50 minute mystery

### ISSUE THREAD

**Issue by ScrawnyRonnie** [psforever/PSF-LoginServer#1042]
For a long time now we've had this lingering issue of the mysterious 'Connection Problem' window that would appear during a larger fight. It always seemed to happen right at or around 50 minutes of in game time. Finally wanting to get to the bottom of this we started doing some testing and discovered how to make it happen. The big question is why?

Here is what you need:
- Around 20 characters (we've had a few more and a few less) all within a certain distance of one another - we believe it to be somewhere in the ~550m range and know by multiple tests that characters farther away than that on the same zone do not experience the issue if they are not in a populated area.
- Time, about 50 minutes to be exact. In the below screenshot these characters (as well as the characters that were logged in from other laptops) one by one had it happen to them in the order they arrived at Zal where all the characters were left. The top right character was there until the first character had it happen, then I left and went far away to the SE. That character **did not** experience the issue after leaving. This shows that something is reset (for lack of a better word) by leaving the proximity of many other characters before that amount of time. That character was then able to go back to where the others were (the DC'd ones were still logged in - most of them ended up having the connection problem window disappear and were able to move around, but not interact with anything, "desynced" as we would call it). I could see them moving around on the non-bugged character that returned to the area. They were unrecoverable and if killed became moving corpses, unaware that they were dead.
![image](https://user-images.githubusercontent.com/73139382/222031189-ffbfe48d-ddb1-4985-8b63-d6cc9e3049e4.png)

**Comment by ScrawnyRonnie** [comment]
Did more testing with this to see if it would also happen if the characters were inside a vehicle. 

Test 1: Two Gals - one TR and one NC. Deth also brought along some characters to stand around.
![image](https://user-images.githubusercontent.com/73139382/222606280-5fdff4ff-6cac-4c0d-aa5a-367119e00433.png)
All clients in this image are NC. All of the TR in the Gal got the 'Connection Problem'. None of the NC did. Deth's characters also did not and we gave it a bit of extra time. For the NC the only thought I have is the zoned while in the Gal and that did something? I then got a new Gal and loaded the NC on another cont, plus brought a few more NC to stand nearby + Deth's 6 TR. Again Deth's TR did not experience the issue, but all the NC did.

Test 2: Three big busses.
![image](https://user-images.githubusercontent.com/73139382/222607169-7d9ca6c6-41e6-463f-81a2-d0640ba823c4.png)
All but three characters experienced the 'Connection Problem'. A few characters were quickly booted and 'left the world' on their own. The three may have survived because the player count dropped down to 15. That may be below the threshold to make this issue occur, but that is only speculation.

Conclusion: Get enough characters near each other, either in a vehicle or not, and after the allotted time you'll have this happen.

**Comment by ScrawnyRonnie** [comment]
After the latest change on https://github.com/psforever/PSF-LoginServer/pull/1054 we did not experience any issues with the DC or increasing ping due to the server's CPU usage spiking. We maxed out at 48 characters (all full clients - no headless). We were not able to see what the usage was at, but it handled that many just fine. Is this one finally over?

**Comment by jgillich** [comment]
Fixed by 65973fee8bc964e08d3e3c57732a20c4ba3d3952
