### ISSUE TITLE
Armor set to 50 upon login

### ISSUE THREAD

**Issue by ScrawnyRonnie** [psforever/PSF-LoginServer#1046]
If you log off while wearing agile or reinforced armor, when you log back the armor will be at 50 instead of it's previous value if it was higher than 50. Testing from full and slightly damaged, it was at 50 on login. If already below 50, it was at whatever value it was at.

It only happens on a new login, not if your character was already persistent.

**Comment by Dethdeath** [comment]
It also refills ammo in all weapons, even the ones that weren't equipped.

https://user-images.githubusercontent.com/77748540/222940616-f3cc42db-d51d-47c8-8cbd-48fbbc28516b.mp4

**Comment by Fate-JH** [comment]
> It also refills ammo in all weapons, even the ones that weren't equipped.
That last part was a request by an earlier community vote.
I hate it.
