### ISSUE TITLE
Med App opens doors remotely

### ISSUE THREAD

**Issue by Dethdeath** [psforever/PSF-LoginServer#1056]
Inoxic found out you can open doors from a distance by firing your med app at them. Seems to work on regular base doors, spawn tube doors and vehicle bay doors. Doesn't work on doors that are locked.
He sent me this video:

https://user-images.githubusercontent.com/77748540/230505312-4781bbca-8779-4b61-bfaa-76772bfea2fc.mp4

**Comment by Fate-JH** [comment]
It doesn't open doors that are locked?  You're certain about that?

**Comment by Dethdeath** [comment]
Yeah I tested it.

**Comment by Fate-JH** [comment]
Can probably fix this by front-loading the distance check with the person who wants to open the door.
Don't know if I want to.  This is an oddly nifty trick as long as it checks all of the correct boxes server-side.

**Comment by Fate-JH** [comment]
Two vectors of unintended consequences caused doors to open.  The first was the doors triggering a "UseItemMessage" packet.  I wrote a distance check to block that, but some doors continued to open when the medical applicator was pointed in their direction.   Those doors that continued to open were ones attached to IFF locks.  The distance check was put on the wrong side of a lock test and the lock test had no distance check of its own.  The locks themselves don't trigger a `USM` packet by having the medical applicator waved in their direction so all's fine with the distance check being put first and foremost before the IFF lock check.

All that's left is to sort out why rearranging elements like this cause a massive delay in door opening for some doors.  "Some doors" "some of the time".
