### ISSUE TITLE
Exploding Vehicles Damage

### ISSUE THREAD

**Issue by xUNTOUCHABLEx** [psforever/PSF-LoginServer#1062]
Exploding vehicles in the courtyard of a base damage people that are inside of the base. For example, when a Lodestar is placed over the spawn room outside of the base walls, when it explodes, it can kill people that are inside of the spawn room in the base.

**Comment by ScrawnyRonnie** [comment]
Me: "How did that kill me through the wall?"
Server: "What's a wall?"
I think that pretty much sums it up 😉

**Comment by Fate-JH** [comment]
Dissecting the world into "indoors" and "outdoors" is on the menu but remains stalled at the planning and logistics stage rather than some stage of production of introduction.
