### ISSUE TITLE
Boomers and other explosions can sometimes not damage players

### ISSUE THREAD

**Issue by Dethdeath** [psforever/PSF-LoginServer#1064]
Boomers do not damage some players until they respawn. I did some tests to try and reproduce it and so far I've found out that it doesn't matter what armor the player is wearing. If you keep blowing yourself up after spawning, usually on the 6th (sometimes sooner) spawn you will be immune to boomers, but the effect is limited, even going some distance outside of the spawn room can make it go away.
Players that have the immune effect can survive boomers and spitfire explosions from both allies and enemies.
So it seems that this is some sort of hidden property of the avatar and not so much the player that put down the boomer. It going away is either distance or time related. More testing needs to be done to find out the exact time or distance.

**Comment by Dethdeath** [comment]
Some more observations:
Waiting like 40 seconds after spawning before doing anything has a high likelihood of giving the immune to explosions effect.
Not even vehicle explosions can damage this player:

https://user-images.githubusercontent.com/77748540/233203564-845883d2-bcab-4e42-ad42-fb72e5b21f4c.mp4

Getting on some sort of elevation can remove the effect (see below). Maybe it's related to the Z coordinate for the player?

https://user-images.githubusercontent.com/77748540/233203639-f5122e64-38b8-46b2-8627-8163be1e9199.mp4

**Comment by Fate-JH** [comment]
A consistent workflow would be best to cort this issue out.  I will attempt the 40s trick and then find the approximate location where you're standing in the video.

**Comment by Fate-JH** [comment]
I think I got it!  The blockmap manages both living players and corpses.  The difference between a corpse and a living player, however, can be muddled as, under certain circumstances, one looks like the other.  Upon entity movement or entity deletion from the blockmap, a "check" is made whereby the game attempts to determine if one is a living player or if one is a corpse and remove the appropriate entity.  If the appropriate entity is not removed, suddenly anything that polls the blockmap may never see something.

And so: the player dies and leaves a corpse.  For a time, the player respawns and walks around, whereupon they are capable of dying to explosives via a blockmap search.  When the corpse of the living player attempts to clean up, the living player is lost by accident.

That's my theory.
