### ISSUE TITLE
Reavers Ramimg ppl kills them 

### ISSUE THREAD

**Issue by lazer1982** [psforever/PSF-LoginServer#1066]
iv done it so many times on PSF - back on Live you could never do that

**Comment by lazer1982** [comment]
ask Raidenmei i ramed in to he so many times and he like !!!!

**Comment by lazer1982** [comment]
you could Ram Players and Damage them But not kill Them from what i remember unless you bailed out and the plane Hit said target dead on, But lets not forget about this as well Talking about the Reaver Raming Problem  https://www.youtube.com/watch?v=OHF0M3WZWbI

**Comment by Fate-JH** [comment]
> you could Ram Players and Damage them But not kill Them from what i remember unless you bailed out and the plane Hit said target dead on

That's actually the vehicle exploding when it hits the ground / something.  My Reavers can't do that because they don't know where the ground is.
In any event, what sort of damage cap should I aim for?

**Comment by Fate-JH** [comment]
Coming back to this, do you guys really not want roadkill oneshots from high health?

**Comment by ScrawnyRonnie** [comment]
Reaver collision damage on infantry is too high and has PS 2 vibes. I used the numbers on the keyboard for different cruise speeds to test different ones and you don't need to be travelling very fast in a Reaver to insta someone in rexo.

[Numbers below are how much health / armor was remaining]

Reaver:
Speed 4: 41 kph / 23 health / 190 armor
Speed 5: 52 kph / dead
Others speeds above this I tested also resulted in death

Wasp:
Speed 4: 47 kph / 67 health / 190 armor
Speed 5: 59 kph / 69 health / 190 armor
Speed 6: 71 kph / 71 health / 190 armor
Max speed with burners: 287 kph / 69 health / 190 armor

Liberator had similar results to the Wasp where going faster caused less damage. The Reaver does have unique killing properties compared to other aircrafts.

**Comment by Fate-JH** [comment]
*laughs*
I was just looked at the `GlobalDefinition` for flying vehicles.  Example of `avatarCollisionDamageMax` for Mosquito and the Wasp - 50 against Infantry, each.  Compare that to the number for theReaver - __750__ against Infantry.
Yeah.  That's a zero that shouldn't exist.
