### ISSUE TITLE
Vehicle gating desync

### ISSUE THREAD

**Issue by Dethdeath** [psforever/PSF-LoginServer#1067]
After going through a warpgate, air vehicle passengers can get desynced from the pilot and see the vehicle as falling constantly or being dragged across the ground at lower heights. For the phantasm, the vehicle cloaking is not synced either.

https://user-images.githubusercontent.com/77748540/234044505-4bd1736b-09d0-4d9d-90f2-4bc0c2879cad.mp4

There's also a problem where both the pilot and passengers cannot bail out or even dismount normally when the vehicle has landed.

**Comment by Fate-JH** [comment]
Phantasm cloak state is controlled through the `VehicleStateMessage` packet, the default movement update packet.  Internally, we do have a state flag on the entity but that updates with `VSM` too.  It's not entirely under my control.  Asides from the case above, might you check that any other situations where you experienced cloak desynced have been cleared?
