### ISSUE TITLE
Lootbags hold doors open

### ISSUE THREAD

**Issue by Dethdeath** [psforever/PSF-LoginServer#1068]
Doors are held open by lootbags now, possibly introduced with the med app door fix?

**Comment by Fate-JH** [comment]
According to file history, in 5428bbbf I added the check for holding the door open like so:
```
Vector3.MagnitudeSquared(entry.door.Position - player.Position) > 15
```
... and in 601bba7 it was changed to:
```
var playerIsBackpackInZone = entry.zone.Corpses.contains(player)
Vector3.MagnitudeSquared(entry.door.Position - player.Position) > 25.5 || playerIsBackpackInZone
```
In 03bc52f5, Mazo changed the check to:
```
var openerIsGone = Vector3.MagnitudeSquared(entry.door.Position - player.Position) > 25.5 || !player.isAlive
if(openerIsGone) { ...
```
When I changed the code for the medapp fix in f4fd78fc, a long chain of code migrations resulted in:
```
val bmap = zone.blockMap.sector(door.Position, maximumDistance)
(bmap.livePlayerList ++ bmap.corpseList).find { ...
```
So this isn't a change so much as it seems to be a return of prior behavior that was wiped away by a simplification (a justified attempt as it was faster than the list comparison, though not the same).  Dead players should hold doors open and I believe corpses are supposed to hold doors open as well.  That's one of the main reasons I wrote code to clean up corpses that have been "sufficiently looted" and no longer hold any equipment.  I have a very unsatisfying memory of standing guard in a Biolab lobby while a former enemy was stuck holding the front door open, first as a dead body then as a corpse, then the door relaxing closed when he finally faded.
