### ISSUE TITLE
If Only I Could Live Longer!

### ISSUE THREAD

**Issue by xUNTOUCHABLEx** [psforever/PSF-LoginServer#1073]
Second wind does not seem to be triggering when its supposed to. It charges up to full and then does nothing.

**Comment by Fate-JH** [comment]
For the record, an initialized Second Wind should activate when you pass below 25 health but have not yet died, awarding 25HP and 25SP.  This is your "supposed to" expectation, yes?

**Comment by xUNTOUCHABLEx** [comment]
Correct, I tested several different weapons dealing different amounts of damage until death for the character when the implant was supposed to be active. The implant never triggered the character died.

**Comment by Fate-JH** [comment]
From my tests, the implant works correctly.  The icon visuals on the hotbar may be incorrect - I can not tell, as I never used Second Wind myself - but the implant does initialize properly with an audio cue and will activate as the target's health falls below 25HP.  I'll change it such that the target's health can start and end below 25HP to make it slightly more accommodating without making it different from its normal operations.

Have the target wear standard exo-suit and stand near the attacker.  They, of course, have the implant installed.  The attacker is armed with a suppressor with 9mm.  Wait until the audio cue for the implant to activate (the icon will still appear dull).  You may want to remove all other implants from the target for this test to ensure the activation cue only fires for Second Wind.
After five shots, the target should have 35HP 30AP, ~75SP.
Upon the sixth shot, the implant will activate, and the target will have 48HP, 26AP, and ~97SP.
If it doesn't activate upon the sixth shot, the target will have 22HP, 26AP, and ~69SP.
