### ISSUE TITLE
MAX Timers

### ISSUE THREAD

**Issue by Dethdeath** [psforever/PSF-LoginServer#1074]
These have been missing for a while.

**Comment by Fate-JH** [comment]
We have MAX timers at home.
![max-timer](https://user-images.githubusercontent.com/16406615/235468570-c6c088c2-975d-4bf3-a691-4353c52b3461.png)

**Comment by xUNTOUCHABLEx** [comment]
The MAX timers reset whenever the player dies. For example, that timer of 4:49 will go to 0 if you died right then and there and respawned. I just tested it by grabbing a MAX suit, doing /suicide, and when I respawned, I could pull the MAX suit again.
