### ISSUE TITLE
Strange avatar names in ANT and AMS after using the warpgate

### ISSUE THREAD

**Issue by Dethdeath** [psforever/PSF-LoginServer#1078]
I first came across this on #1076 :
![PSScreenShot0007](https://user-images.githubusercontent.com/77748540/236110978-99ff85f0-4c24-4ce9-9bdc-ce0d777b01c7.png)

But I've seen something like this before on the regular server, so I figured I'd try to reproduce it there too. With success.
The avatar has a weird name and when they get out of the vehicle, their movement is not tracked at all:

https://user-images.githubusercontent.com/77748540/236113490-493be3ca-c427-4ee9-b592-24dc286b7072.mp4

When the ANT is deconstructed here, the player that was standing inside it is invisible:

https://user-images.githubusercontent.com/77748540/236113530-941e6f63-c07b-40a7-a767-e1b0afca6588.mp4

I've tried to reproduce the issue while being on foot and while driving a few other vehicles, but so far it only occured when driving an ANT or AMS.

A big chunk of the AMS is missing here as well, which could mean it has something to do with the vehicle deployment state?
![PSScreenShot0009](https://user-images.githubusercontent.com/77748540/236114463-84fe4312-381a-4378-a29a-aa308b94873a.png)

Additional observations:
On the test server I had 4 characters use the warpgate and load onto the continent one by one, 3 of them were driving an ANT as seen in the first screenshot. The character that loaded onto the continent first saw all the names correctly. The 2nd character saw 2 names correctly, the 3rd 1 name and for the 4th character all names were wrong.

Relog or suicide fixes the problem btw.

**Comment by Dethdeath** [comment]
Some more things that might be of interest.
Zipline sound: 

https://user-images.githubusercontent.com/77748540/236948267-da8214e5-1b0d-4d1a-b93d-149c2a1fbe9d.mp4

Player perspectives:
![pers1](https://user-images.githubusercontent.com/77748540/236948337-d88e1ec9-14a4-42a7-8a5a-19888d30a296.png)
![pers2](https://user-images.githubusercontent.com/77748540/236948342-209faaa2-f06f-4e7c-9b53-e5c9fc0dee4a.png)

**Comment by Fate-JH** [comment]
How consistently can this break? especially, how consistently can you break the AMS model?
I am not certain if I can work a solution into the event PR in time, or produce a separate PR for it in time, but I think that should be the best thing to attempt.

**Comment by Dethdeath** [comment]
The AMS model breaks almost every time.
Whoever gates to the continent first with an AMS will usually appear broken to anyone who gates after them. It also doesn't matter what the person after them is driving. If there was a person on the continent before the AMS gated, this person will see the AMS and player name properly. Anyone gating after that will not see the AMS + driver correctly. On the off chance that they do see the AMS properly and it deploys for example, the driver name will still be broken for them.
