### ISSUE TITLE
Invisible vehicles and characters

### ISSUE THREAD

**Issue by ScrawnyRonnie** [psforever/PSF-LoginServer#1079]
During today's vehicle fight there were many occurrences where someone's vehicle was invisible to other players, but not _all_ other players. I later did some testing and confirmed a (or the only?) scenario where this will happen. Here is how it happens:
- Player A is not in a vehicle. Player B is.
- Player B's vehicle is destroyed and they die and respawn.
- Player A pulls a vehicle while Player B is respawning/on spawn select map
- When Player B respawns they will not see Player A's vehicle. They will see Player A's name/health at the location they were last known by Player B.
- If Player A exits the vehicle Player B can see their name moving around and are able to damage them at any point as well.
https://user-images.githubusercontent.com/73139382/236715545-84ce4805-87e1-4f96-86be-9d43a22bb764.mp4
Whatever it is fixes itself if Player A gets into a new vehicle.

**Comment by Dethdeath** [comment]
I think this might be how the guy with the beamer killed people inside a vehicle a few months ago.

**Comment by ScrawnyRonnie** [comment]
As far as I know from my experience and what others shared, vehicles were the only thing that couldn't be seen (I would assume only if the vehicle spawned while they were respawning based on the additional testing and findings I did).
