### ISSUE TITLE
Vehicle wrecks appear on the minimap and have full health

### ISSUE THREAD

**Issue by Dethdeath** [psforever/PSF-LoginServer#1085]
![wreck](https://github.com/psforever/PSF-LoginServer/assets/77748540/9ab5d3c9-8c0f-43f3-99f7-7b54d1932c6c)

https://github.com/psforever/PSF-LoginServer/assets/77748540/dee7f05c-0938-4169-93cd-8cc90122a2d5

It appears when you pull a new vehicle and it seems like the vehicle's previous owner has a higher chance of seeing the wreck like this, others don't always see its healthbar. For some reason this stuff doesn't show while on foot.

**Comment by Fate-JH** [comment]
Has there been any change in this behavior?

**Comment by Dethdeath** [comment]
Still the same.

**Comment by ScrawnyRonnie** [comment]
I think this has to do with a vehicle becoming ownerless. With vehicles that are not destroyed, as soon as the owner leaves the zone or becomes the owner of another vehicle, the previous vehicle looks like it is heavily damaged (sparking/lights flashing), but the health bar shows full. If it is damaged, the health bar doesn't go down.
![image](https://github.com/psforever/PSF-LoginServer/assets/73139382/67f8ad0c-f85e-47b4-a077-4beef190be99)
The player on the right was the owner and pulled a new vehicle.
The player on the left side saw it in this state as well, but after leaving the zone and returning that fixed the model/health bar.
