### ISSUE TITLE
Capturebase doesn't work with typed base names on the battle islands

### ISSUE THREAD

**Issue by Dethdeath** [psforever/PSF-LoginServer#1089]
On each of the battle islands, when you type /capturebase basename empire
You get this error:

Error - basename is not a valid building name.

**Comment by Fate-JH** [comment]
It's important to note that internally the Nexus facility is named "Nexus_base", and the other islands use either colors ("Blue_Base") or the military alphabet ("Base_Alpha") in their naming schemes.  The properly-named facilities are found on Oshur Prime.

**Comment by ScrawnyRonnie** [comment]
Here are all of them as Fate mentioned:
**Extinction**
Mithra - Blue_Base
Yazata - Red_Base
Hvar - Indigo_Base

**Ascension**
Zal - Base_Alpha
Rashnu - Base_Bravo
Sraosha - Base_Charlie

**Desolation**
Dahaka - Red_Base_97
Jamshid - Blue_Base_97
Izha - Indigo_Base_97

**Nexus:**
Atar - Nexus_base
