### ISSUE TITLE
Turrets, automatic turrets, no automatic attack

### ISSUE THREAD

**Issue by takyzheng** [psforever/PSF-LoginServer#1101]
Turrets, automatic turrets, no automatic attack

**Comment by Fate-JH** [comment]
Turret autonomous behavior is not possible in the current sim and it will take a lot before they could become possible.
Personally, I won't be wokring on this any time soon.

**Comment by takyzheng** [comment]
Thank you very much for your reply. We are a hobbyist organization from China. We have more than 20 people playing games every night. If you are interested, we are available after 8 PM Beijing time. Our server address is www.netarmory.net port 51000. We're all looking forward to improving the game. Thank you so much for your dedication to this game.
