### ISSUE TITLE
Crashes maybe linked to opening doors under certain conditions

### ISSUE THREAD

**Issue by 700hours** [psforever/PSF-LoginServer#1107]
Topic:
Opening a door sometimes leads to a crash, although crashes in general may be for other reasons. Here's an instance of someone who crashed.

![image](https://github.com/psforever/PSF-LoginServer/assets/31488826/ef2c2b6e-eadf-4aa8-8cee-caa2b039759b)
In a MAX suit while fighting was occurring at Mekala, Amerish. Afaik there was a Deliverer in the field, and fighting at the base proper.

Another instance of this crash happened while opening the VBay door at Mekala. Today we had a series of vehicles in the field, while crashes happened intermittently.

Reproduction:
Unsure, but before the doors seems to fully open, maybe while rendering the environment outside, or even inside seems to be one cause. Maybe area loading. I will attach an error log of the VBay door instance.

[planetside_crash_6-4.log](https://github.com/psforever/PSF-LoginServer/files/11646569/planetside_crash_6-4.log)

**Comment by Resaec** [comment]
I also had this happen when opening too many doors successively while testing GUIDs.
After teleporting to ~170-250 doors the client crashes. Teleporting to a Warpgate (they are often far away from previous doors) seems to reset the "counter" allowing >700 door visits.
Receiving too many door states from doors far away could fill up the clients door state storage.

**Comment by Mazo** [comment]
Probably related to the portal system in some way. Doors control occlusion of entire segments of bases behind them when closed or opened.
