### ISSUE TITLE
Spectator issue

### ISSUE THREAD

**Issue by Dethdeath** [psforever/PSF-LoginServer#1111]
Someone was spectating a fight yesterday and it caused a player to get kicked from the server. It turns out it happens when the person spectating exits spectate mode and then dies of something, like /suicide. It also seems to be timing related? I basically did /suicide right after coming out of spectate mode when testing.

![nice](https://github.com/psforever/PSF-LoginServer/assets/77748540/65ca8f23-fd64-419c-9130-e9ab8a827d20)

I used a Dragon during testing because of the damage over time, but that might not matter if it just looks at who last damaged the spectator.

**Comment by Resaec** [comment]
I can recreate the last hitter counting as the killer on suicide, but it will not trigger a kick for me.
Is there more information?

**Comment by ScrawnyRonnie** [comment]
There is another reason this happens and it relates to when spectator mode is enabled and when a player arrives in that zone. If someone is in spectator mode and a player arrives in the zone **after** they are already in spectator mode, the spectator is visible to them, but frozen in place where the spectator was when that new player arrived. Players that are already in that zone cannot see the spectator. Toggling spectator off and on fixes it for the new player.
![image](https://github.com/psforever/PSF-LoginServer/assets/73139382/a4dc02ea-ec56-45fe-bb0d-6be84f8a4bf6)

**Comment by ScrawnyRonnie** [comment]
This same thing also happens with deconstructing. Player A deconstructs. While A is on the map, player B arrives in the zone. Player B will see player A. I almost said it only happens if a player arrives in the zone after deconstruction, but it also does this if player B is far enough away on the map when player A deconstructs. Player B can travel to A and see them.
![image](https://github.com/psforever/PSF-LoginServer/assets/73139382/b58d0fa6-f8da-47f5-b6ac-5f905b682a61)

**Comment by Dethdeath** [comment]
Adding this here for now, could make a separate issue later if needed.

Spectators can get into vehicles if they purchase them a certain way, they should probably just not be allowed to get into the vehicle buying queue. Here's a video:

https://github.com/psforever/PSF-LoginServer/assets/77748540/c0b27eb9-9fa8-4d5f-86e9-21cedd45f51f

After dying in a vehicle they can still move around during the respawn screen.

I also noticed that spectators get an oxygen bar when they go underwater, when it gets to 0 nothing happens. This is a really minor thing that can probably be ignored as it doesn't lead to anything bad.

**Comment by ScrawnyRonnie** [comment]
Prevent someone in spectator from purchasing a vehicle. Added to same logic as the purchase timer.
https://github.com/psforever/PSF-LoginServer/assets/73139382/e7ce9b8a-466c-407d-897d-75474345901f

**Comment by Dethdeath** [comment]
Nice.
