### ISSUE TITLE
Can't get this game to work at all keep getting unknown connection error

### ISSUE THREAD

**Issue by Druout** [psforever/PSF-LoginServer#1140]
![image](https://github.com/psforever/PSF-LoginServer/assets/137722458/233a1f13-e228-411a-87f4-07b8e4ec0f39)
Any help would be appreciated, but so far nothing works; setting launcher and game to run as admin had no effect. I get either "Unknown Connection Error" or "Unknown Login Error".

**Comment by ScrawnyRonnie** [comment]
Looks like the server is down.

**Comment by lazer1982** [comment]
yup its down on my end as well gess FateJH is working on it.

**Comment by Druout** [comment]
whew well at least that means I have a chance some other time hopefully; thanks guys

**Comment by Dethdeath** [comment]
Should work now.

Btw if you aren't on our discord yet, you can find it at https://discord.gg/0nRe5TNbTYoUruA4
