### ISSUE TITLE
/capturebase causes problems with already hacked bases.

### ISSUE THREAD

**Issue by KingFeraligatr** [psforever/PSF-LoginServer#1148]
I've know for several years that using /capturebase on an already hacked base could cause problems and it was something you just didn't do. Fixing this would make using this command safe on already hacked bases.

**Comment by Fate-JH** [comment]
Can you provide some details in regards to how hack-in-progress facilities were spoiled by using this command?

**Comment by Dethdeath** [comment]
I think the timer would keep going and in some instances that meant you weren't able to resecure it. I've tested it on various continents on #1173 and it seems to all work as it should.

**Comment by ScrawnyRonnie** [comment]
Yeah I think this was already fixed in #1147
