### ISSUE TITLE
Cavern Doors do not respond

### ISSUE THREAD

**Issue by Rizzarak** [psforever/PSF-LoginServer#1151]
Most of the caverns (Except Supai, havent checked yet) have doors to the control console and building entranceways that remain closed/locked when approached. It's mainly on the AT plants and Module buildings that one set of doors will not open for the control room area.

**Comment by Fate-JH** [comment]
Are you talking about IFF locked doors?

**Comment by Rizzarak** [comment]
No in the caves there is no IFF locked doors

**Comment by Resaec** [comment]
Can you provide location data (/loc) for the affected doors?
I'm working on fixing the doors and have not found any bugged doors in the caves except on Adlivun (see #1152).
Thanks

**Comment by Rizzarak** [comment]
Byblos - Module South inner eastern door - just checked it and it
doesn't open

I will go through them as they become available or try to today and give
you a more detailed location.

**Comment by Resaec** [comment]
Alright, I added 4 Byblos doors to my ongoing PR #1152

**Comment by Rizzarak** [comment]
bandicam 2023-12-12 13-32-40-447.mp4
<https://drive.google.com/file/d/1no9YwZdyRpf5RwUjrL0kj2LFDmqh4WUc/view?usp=drive_web>
Add Annwn to your list - i could not zone in from amerish to that cave. I
recorded it so you could see

**Comment by Resaec** [comment]
@Rizzarak he, thank you, but your video is not set to public yet.

Zoning will need to be fixed in another PR once we find the problem.
Please remember to keep an issues restricted to one kind of problem so that the information on other problems is not lost once the related PR closes this issue.
There is likely already another issue for zoning since it is a known topic internally.

**Comment by Rizzarak** [comment]
bandicam 2023-12-12 13-40-47-890.mp4
<https://drive.google.com/file/d/1B1INtr6ymIYJ-B-Uw0FYGNel1rPXUA67/view?usp=drive_web>
Yeah Annwn is bugged bad this is from esamir

**Comment by Rizzarak** [comment]
https://drive.google.com/file/d/1K6L20C38vp6-OwnBfQySkIJoenvkCG65 - Amerish
Attempt

https://drive.google.com/file/d/1mQWD6X8FwjUpAfz6hEt5HSW-ZoV7-cFb - esamir
attempt

**Comment by ScrawnyRonnie** [comment]
The zoning issue with caves had a fix in #1146 From my testing I haven't had that happen anymore.

**Comment by Rizzarak** [comment]
https://drive.google.com/file/d/1ifORXdz_LS8ToHaencMV3oBqS4y0D_WG -
Drugakan Module north building

**Comment by Rizzarak** [comment]
Let me try a different empire then

**Comment by Rizzarak** [comment]
https://drive.google.com/file/d/1hFHCEjvzlVnISiWxJIu20mGEXD0H52-3 - From
Hossin this time as VS.

You can address it after I get into the other caves, so no worries there.

**Comment by ScrawnyRonnie** [comment]
The zoning fix is not on the main server yet. Try getting on port 61009. The same caves might not be open though...

**Comment by Rizzarak** [comment]
Correct and its 7 hours till Supai opens so i going to do some other things
-  i set my timer so hopefully i will be around when it opens

**Comment by Rizzarak** [comment]
I connected through port 61009 to a different server name.

Character - Gonadoit - NC

https://drive.google.com/file/d/1xLlLqwUxYwB-h1PRA_pDjAkObwB6fqSs - zoning
into hunhua got that annoying movement bug

**Comment by Rizzarak** [comment]
All Hunhau doors are good to go.

**Comment by Rizzarak** [comment]
Adlivun Cave

https://drive.google.com/file/d/1vWK5yHHeRP-NahVErYPG3Jvtub__CXym - Module
Building Southwest
