### ISSUE TITLE
Kills not counting

### ISSUE THREAD

**Issue by ScrawnyRonnie** [psforever/PSF-LoginServer#1154]
Some kills are not rewarding xp or adding to the K/D HUD or stats window. For the player that dies it also doesn't count their death in the K/D HUD. It's as if the kill never happened, except for the part where it shows in the feed and someone dies. So far no rhyme or reason has been discovered, but it happens frequently.

**Comment by lazer1982** [comment]
To add on to this tested it with a fell Alts of mine Base Cap Rescues don't grant XP even with 9 kills
![PSScreenShot0049](https://github.com/psforever/PSF-LoginServer/assets/99909749/b1414c99-827c-4972-8670-1fa10d17f68d)
