### ISSUE TITLE
Vehicle terminal doesn't allow for more purchases after player is removed from queue

### ISSUE THREAD

**Issue by Dethdeath** [psforever/PSF-LoginServer#1155]
When a player gets removed from the vehicle queue (when they move too far away from it for example), they cannot use that vehicle terminal again to purchase another vehicle. Only dying and zoning appears to fix it.

**Comment by Fate-JH** [comment]
The culprit appears to be unresolved order fulfillment conditions.  According to the log, it complains that the order hadn't yet been fulfilled so some other step in the order fulfillment process must eventually reset the flag.  Checking the conditions for handling `BuyVehicle` transactions in `SessionTerminalHandlers`, the guard flag is never reset during the step where the spawn pad is contacted, which was probably also blocking a line of code that allowed one to update their order if it was caught before reaching the head of the queue.
