### ISSUE TITLE
Juggernaut EMP kills show up as "Apc Tr"

### ISSUE THREAD

**Issue by Dethdeath** [psforever/PSF-LoginServer#1162]
![apctr](https://github.com/psforever/PSF-LoginServer/assets/77748540/18cd5e60-65eb-4cd8-aa8c-de301084d8de)

I assume the same might happen with the NC/VS variants.

**Comment by Fate-JH** [comment]
I should hope not.
The Vindicator is "Apc Nc" and the Leviathan "Apc Vs".
My code may be bad, but not that bad.

**Comment by Fate-JH** [comment]
Also, the EMP looks to have exploded something too close to a spitfire and its resulting explosion killed a player.  Is that death acceptable shorthand to immortalize the legacy of player test765432?

**Comment by Dethdeath** [comment]
Yeah. For my test I put one player next to some mines on one side of the Juggernaut and the other side had a spitfire + mine. The easier way to reproduce this issue is to use the EMP and have players in range /suicide right after.
