### ISSUE TITLE
Oversized inventory favorite creates invisible items

### ISSUE THREAD

**Issue by Dethdeath** [psforever/PSF-LoginServer#1165]
Came across this during the fight on Sunday. Got rid of the Rexo cert at one point and ended up with invisible items in my inventory. Seems to be a problem with a favorite trying to cram items into an inventory that is too small for it.
Video shows what kind of a mess it creates:

https://github.com/psforever/PSF-LoginServer/assets/77748540/8bfdc4a5-6138-4691-9779-046e4d9e1169

I tried reproducing this with a MAX favorite and when I loaded it I got DCed. I waited for the session to time out and did it again, this was the result:

![MAXfav](https://github.com/psforever/PSF-LoginServer/assets/77748540/e418aec7-7ff6-44ab-aba9-c6fcef86126b)

Zoning also doesn't work when the inventory is filled up like this.

Reproduction steps:
-Create a Rexo/MAX favorite that has all slots filled.
-Get rid of the armor certification.
-Load the favorite while having a smaller inventory, so usually agile armor (PJs probably work too).

**Comment by Fate-JH** [comment]
These actualy seem like two different issues.  The MAX issue, in particular, exists because those weapons were never intended to go into the inventory and I never gave it a proper icon size.  The weapon is filling up a 1x1 square.
