### ISSUE TITLE
IFF Blocking a Rek 

### ISSUE THREAD

**Issue by lazer1982** [psforever/PSF-LoginServer#1168]
IFF lock is messed up.  It Opens for Owning faction,.  Emy Faction goes to try and hack it and Fails to open,  When Base is Hacked Iff is by passed and works as intended.   

https://streamable.com/sf42rl
0 to 12 secs is TR. 12 to 23 is NC and rest is VS
![tara gen door](https://github.com/psforever/PSF-LoginServer/assets/99909749/778d913b-93fd-413c-9ed9-a05ba4c085ab)

**Comment by theonetrueduddy** [comment]
Testing this on our current live patch;
- Was able to replicate on Tara generator door, was unable to replicate on other doors
- Was unable to replicate on the nearby Wakea

I suspect that this has something to do with the base being neutral or the gen being blown previously? Last night the gen/tubes were down at Tara and the base was neutral, I presume Lazer came and captured the base (to get that sweet ANT BEP) and then discovered this.

Wanted to try another base I knew had been neutral recently but couldn't recall the exact one, so would recommend making a base neutral and then capturing it (and maybe blowing the gen) to attempt to reproduce.

**Comment by lazer1982** [comment]
I Ran in to this yesterday during the fight, The base was VS when i logged on, so something with ownership? 
The Base you are talking about is Mukuru on Cyssor since i filled to today yea for --> (to get that sweet ANT BEP) got br16..

**Comment by lazer1982** [comment]
did in fact find somthing with the Cave Locks as well that is Odd.. 
![Cave lock](https://github.com/psforever/PSF-LoginServer/assets/99909749/e70a3928-ddb6-4db4-a43a-52255d2b2442)

**Comment by ScrawnyRonnie** [comment]
The tower roof IFF unlocks the gen room door. Triangle of IFFs unlocking the wrong doors. Illuminati confirmed

**Comment by lazer1982** [comment]
at least we know where that tower top IFF goes to now !! (
