### ISSUE TITLE
Cannot exit Galaxy/Lodestar cargo hold after using a warpgate

### ISSUE THREAD

**Issue by Dethdeath** [psforever/PSF-LoginServer#1182]
The vehicle passenger in the cargo hold cannot exit the aircraft after warping to another continent via a warpgate. Bailing out doesn't work, the pilot cannot kick the vehicle out and getting out when landed doesn't work either.
If the pilot then deconstructs their vehicle, the passenger gets sent to white hell and their client freezes.

Lazer mentioned his cargo hold vehicle passenger got DCed after warping to another continent. Perhaps this is related.

**Comment by lazer1982** [comment]
had this hapen to me as well trying to go fill a base on esmire from sanc with a Gal and a Loadstar, i load the char back in and this hapens.   and yea that ant was floating in Mid air,
 untill i taped it with a Reaver was just Visable on The one client  as you see 2 there
![ant in air](https://github.com/psforever/PSF-LoginServer/assets/99909749/e9779292-eb88-4d69-8904-30ff67f49407)
