### ISSUE TITLE
Yellow circles and text for owned CE

### ISSUE THREAD

**Issue by Dethdeath** [psforever/PSF-LoginServer#1216]
This is missing.

Screenshots taken from old footage:

![OwnedCE](https://github.com/user-attachments/assets/5016fbac-685c-4a91-965d-64a84072517e)

**Comment by Fate-JH** [comment]
The yellow rings technically did work at one point but I think a previous change to the transcoders that turn packets into bits and bytes modified the field for ownership.  Indeed, if I look at a modern example of the packet for creating deployables, one that is affected by changes to the transcoders, the field for ownership translates into a value that is not related to the technical owning player anymore.  I'll need to re-examine the samples and determine how to correct the packet in such a way that it functions properly.
