### ISSUE TITLE
Missing vehicle deployment status messages

### ISSUE THREAD

**Issue by Dethdeath** [psforever/PSF-LoginServer#1220]
There's missing messages regarding vehicle deployment status. The deployment messages are missing for AMSes, ANTs and Routers.

There's also a message missing for AMSes being too close to each other on the same empire.

What these used to look like:

![deployed](https://github.com/user-attachments/assets/e2b77ede-1728-49b1-b287-428e35c55c6f)

![tooclose](https://github.com/user-attachments/assets/c449474a-72e7-4f3b-a9d5-c6d9510ac8ec)

**Comment by Resaec** [comment]
Should be `@DeployingMessage`, `@UndeployingMessage` and `@nodeploy_ams`

**Comment by Fate-JH** [comment]
Do you know the chat message type of those strings? I assume `UNK_227` since it's incredibly common, but a more uncommon message type might be utilized by deployment messages.
