### ISSUE TITLE
Missing spawn tube sound

### ISSUE THREAD

**Issue by Dethdeath** [psforever/PSF-LoginServer#1229]
The sound when players spawn is missing from spawn tubes.

The soundfile for this is called "respawn_use.wav", perhaps that indicates something about the inner workings of spawn tubes.

https://github.com/user-attachments/assets/44070970-a712-462a-bda5-3784009806d9

**Comment by Fate-JH** [comment]
Does the AMS have a spawn sound?

**Comment by Dethdeath** [comment]
No.

The AMS has something called "Spawn_effect" which used to show up around players spawning at an AMS.
(1:23:37)
https://www.youtube.com/watch?v=JeTYFBPg6kk&t=5017s

The effect also showed up at spawn tubes, can be seen in that same video at 1:27:30
