### ISSUE TITLE
Automatically determine external IP using UPnP

### ISSUE THREAD

**Issue by pschord** [psforever/PSF-LoginServer#16]
Here's a cool powershell example that works: https://stackoverflow.com/questions/34247757/why-is-the-external-ip-not-returned-from-a-upnp-getexternalipaddress-query-using

This issue was noticed when trying to host a game server behind a router. A simpler way to handle this would be to provide a configuration file where people could provide a public IP or domain name.

But hey, one can dream, right?

**Comment by pschord** [comment]
Also, automatically enabling port forwarding would be pretty nice.

**Comment by Shadow41190** [comment]
I think. I may have a way to get the login server to listen for incoming traffic. as for the port. it would still have to be added to the port forwarding on the router manually. at the moment I am having issues getting my own ports to open. once I get that fixed. I will see if what I have worked and let you know. I will also take a look at your PowerShell link and see what I can do. :)

**Comment by pschord** [comment]
An idea I had was to have a central matchmaking server that each world server would register with. This matchmaking server would *know* the public IP of the server just based off of internet traffic. Then a centralized login server could run an distribute world connections to many servers off of a list.

I imagine this would be similar to server selection in something like Counter Strike

**Comment by jgillich** [comment]
> provide a configuration file where people could provide a public IP or domain name.

This we now have, but UPnP is irrelevant in a data center environment and with IPv6 becoming more prevalent it's also less relevant for home use. So I'll go ahead and close this, if anyone feels differently feel free to reopen.
