### ISSUE TITLE
Map9 9.scala:21: not found: value MapScale [error]     Scale = MapScale.Dim4096

### ISSUE THREAD

**Issue by Nesasoci** [psforever/PSF-LoginServer#277]
I can't compile the server, the following errors occur:

`E:\psforever\PSF-LoginServer-master>sbt pslogin/run
[info] Loading project definition from E:\psforever\PSF-LoginServer-master\proje
ct
[info] Set current project to root (in build file:/E:/psforever/PSF-LoginServer-
master/)
[info] Compiling 36 Scala sources to E:\psforever\PSF-LoginServer-master\pslogin
\target\scala-2.11\classes...
[error] E:\psforever\PSF-LoginServer-master\pslogin\src\main\scala\zonemaps\Map9
6.scala:20: not found: value MapScale
[error]     Scale = MapScale.Dim4096
[error]             ^
[error] E:\psforever\PSF-LoginServer-master\pslogin\src\main\scala\zonemaps\Map9
7.scala:20: not found: value MapScale
[error]     Scale = MapScale.Dim4096
[error]             ^
[error] E:\psforever\PSF-LoginServer-master\pslogin\src\main\scala\zonemaps\Map9
8.scala:21: not found: value MapScale
[error]     Scale = MapScale.Dim4096
[error]             ^
[error] E:\psforever\PSF-LoginServer-master\pslogin\src\main\scala\zonemaps\Map9
9.scala:21: not found: value MapScale
[error]     Scale = MapScale.Dim4096
[error]             ^
[error] four errors found
[error] (pslogin/compile:compileIncremental) Compilation failed
[error] Total time: 32 s, completed 2019-10-11 14:05:05`

I didn't change anything, just followed the instructions. How do I fix that?

**Comment by SouNourS** [comment]
Last merge did that bug, until a PR change that, you can do : 

in /pslogin/src/main/scala/zonemaps/Map96.scala   
change "import net.psforever.objects.zones.ZoneMap"
to "import net.psforever.objects.zones.{MapScale, ZoneMap}"

same for Map97.scala, Map98.scala, Map99.scala

**Comment by pschord** [comment]
Fixed in the latest master version.
