### ISSUE TITLE
Refactor WorldSessionActor

### ISSUE THREAD

**Issue by pschord** [psforever/PSF-LoginServer#278]
It's been said for a while at this point, but [WorldSessionActor](https://github.com/psforever/PSF-LoginServer/blob/master/pslogin/src/main/scala/WorldSessionActor.scala) needs to be broken up into smaller files. It has grown to nearly 10K lines of Scala, which is dense as it is. Maintaining and understanding this file is likely next to impossible for new developers. It's so big that TravisCI fails to compile it with code coverage enabled!

Nearly all of the player business logic for PlanetSide is in this single file. Let's start to logically divide this up into smaller sub-files.

**Comment by Fate-JH** [comment]
Resolved in #1015, for better or for worse.
