### ISSUE TITLE
Unhandled Cryptopacket Bitvector

### ISSUE THREAD

**Issue by ghost** [psforever/PSF-LoginServer#280]
Resulted in an "Unknown Login Error" message during Login Progress.
![image](https://user-images.githubusercontent.com/888142/66679830-c9d2ca00-ec34-11e9-98f8-dbd0df5fea72.png)

See debug log: pslogin-debug_2019-10-11_20-45-09.log

`[ERROR] CryptoSessionActor - Could not decode packet in state CryptoSetupFinishing: unmarshal_crypto_packet/obj_type?: expected constant BitVector(8 bits, 0x10) but got BitVector(8 bits, 0x01)
[ERROR] CryptoSessionActor - Could not decode packet in state CryptoSetupFinishing: unmarshal_crypto_packet/obj_type?: expected constant BitVector(8 bits, 0x10) but got BitVector(8 bits, 0x01)
[ERROR] CryptoSessionActor - Could not decode packet in state CryptoSetupFinishing: unmarshal_crypto_packet/obj_type?: expected constant BitVector(8 bits, 0x10) but got BitVector(8 bits, 0x01)`

**Comment by jgillich** [comment]
Probably long resolved and user was deleted so there's nothing actionable here.
