### ISSUE TITLE
Facilities - Facility Status - UI - Facility Status UI for surface Bases, their Flag Icons, and NTU charge will not properly update within a game session

### ISSUE THREAD

**Issue by NickPSF** [psforever/PSF-LoginServer#338]
Facility Status UI for surface Bases, their Flag Icons, and NTU charge will not properly update within a game session.

**Comment by Mazo** [comment]
This is likely down to the GUID issue with buildings.

**Comment by NickPSF** [comment]
Not seeing this anymore. Closing for now.
