### ISSUE TITLE
Crash - CTD - Zone Transfer - When characters zone, the client often crashes to desktop during the Loading Screen

### ISSUE THREAD

**Issue by NickPSF** [psforever/PSF-LoginServer#341]
When characters zone, the client often crashes to desktop during the Loading Screen.

**Current Result:** The game client will commonly crash to desktop during zone transfer.
**Expected Result:** The game client should never crash during zone transfer.

**Reproduction Steps:**

- Using the /zone command, transfer between different continents repeatedly (you can spam /zone z2 /zone z3 /zone z2 /zone z3 etc)
- Observe crash to desktop

**Comment by Mazo** [comment]
It's probably not worth us raising client issues as github bugs unless we have reproduction steps for them, otherwise the issues will just linger forever as there's not really anything we can do.

**Comment by NickPSF** [comment]
Well, this is a high occurring crash bug, one that really never occurred on Live. Technically, we do have crash logs and repro steps (just zone repeatedly -- there seems to be no rhyme or reason for this occurring, although Cave zones may induce it more quickly, or perhaps, logging onto a different character in the same session, although just plain old zoning to normal zones will cause it as well).

This is a critical issue because it's a common crash occurring during the main gameplay loop of zone transfer.

**Comment by Mazo** [comment]
Unfortunately that doesn't really work for reproduction steps though. Just zoning repeatedly gets us no closer to understanding *why* it's happening. If we could get exact reproduction steps that trigger it we can start narrowing it down, but other than that there's no chance of us finding it other than by pure blind luck.

**Comment by NickPSF** [comment]
Noted. Will investigate further.

**Comment by NickPSF** [comment]
This doesn't seem to be an issue any longer. Closing out for now.
