### ISSUE TITLE
Gating - Warpgates - Geowarps - Geowarps do not warp players to Cavern zones

### ISSUE THREAD

**Issue by NickPSF** [psforever/PSF-LoginServer#342]
Geowarps do not warp players to Cavern zones

**Comment by NickPSF** [comment]
The cave timers appear to be somewhat functional client side? Is there anything we can do here?

**Comment by Mazo** [comment]
Currently no, they would need a lot of work to be properly functional. The only reason the timers are working client side on 51200 is because Sounours has added a few lines to send an extra packet with essentially an arbitrary timer.

51000 has no cave timers.

**Comment by NickPSF** [comment]
Any hacky solution for this currently?

**Comment by Mazo** [comment]
Beyond the hacky "turn off the geowarps"?

Not yet. I'll try and take a look at some point but until proper cave rotation is in I doubt we can do better than sending them to the currently linked cave.

**Comment by Mazo** [comment]
Also it's probably for the best they stay off for now, until we find a fix for the zoning crash from the turrets.

**Comment by NickPSF** [comment]
Sending them to the currently linked cave is good enough for me.

**Comment by Dethdeath** [comment]
Geowarp zoning is much more stable now, but you can still get a client crash every once in a while. There's also an issue where you can get sent back into the cave instantly when zoning to a regular continent. This bypasses the "you have left the protective shield around the warpgate" message and action which is usually required to go back through.

**Comment by Fate-JH** [comment]
Going to close this because the core issues is more or less solved.
Issues that arise from the geowarp gates working should become their own tickets.
