### ISSUE TITLE
Vehicles - Advanced Hacking - Vehicle Jacking - After jacking an enemy Vehicle, the hacker will not see the vehicle ownership change clientside, despite changing for other players serverside

### ISSUE THREAD

**Issue by NickPSF** [psforever/PSF-LoginServer#350]
After jacking an enemy Vehicle, the hacker will not see the vehicle ownership change clientside, despite changing for other players serverside.

Occurring on Master server (51000).

**Comment by Mazo** [comment]
Likely fixed in #348

**Comment by NickPSF** [comment]
Fixed
