### ISSUE TITLE
Crash - Runtime Error - When /zone'ing to Annwn (ugd05 / c5), the game crashed with a Microsoft Visual C++ Runtime Library "Runtime Error!" message

### ISSUE THREAD

**Issue by NickPSF** [psforever/PSF-LoginServer#362]
When /zone'ing to Annwn (ugd05 / c5), the game crashed with a Microsoft Visual C++ Runtime Library "Runtime Error!" message.

![image](https://user-images.githubusercontent.com/59997100/79530261-781c5980-8034-11ea-85f8-8e64a5ed8f9c.png)

**Comment by Mazo** [comment]
Likely fixed by all the cavern GUID changes, closing for now. Can reopen if issue reoccurs.
