### ISSUE TITLE
Implant - Ordering/Default fix

### ISSUE THREAD

**Issue by NickPSF** [psforever/PSF-LoginServer#370]
Slot 1: Surge
Slot 2: Audio Amp
Slot 3: Enhanced Targeting

Audio Amp is used in all situations, Darklight is situational. The current ordering will also break everybody's hotkeys.

**Comment by Fate-JH** [comment]
What's this ticket about?

**Comment by NickPSF** [comment]
> What's the first part of this ticket about?

Expected behavior

**Comment by Mazo** [comment]
@Fate-JH see #374

**Comment by NickPSF** [comment]
Fixed on branch CI
