### ISSUE TITLE
Vehicles - Vehicle Terminals - Vehicle Queue - The vehicle queue at a vehicle terminal can become blocked and unable to be cleared with the /destroy command

### ISSUE THREAD

**Issue by NickPSF** [psforever/PSF-LoginServer#379]
The vehicle queue at a vehicle terminal can become blocked and unable to be cleared with the /destroy command.

Occurred during sizable 51000 playtest on 4/19/20 at Bastet Amp Station.

**Comment by Mazo** [comment]
Might be fixed in #376 (3af9c15)

**Comment by NickPSF** [comment]
Probably needs live regression testing during a play test. Keeping this open for now.

**Comment by Mazo** [comment]
Can we close this @NickPSF ?

**Comment by NickPSF** [comment]
Yep, closed
