### ISSUE TITLE
Healing - Backpacks - When healing a backpack, it opens the Inventory

### ISSUE THREAD

**Issue by NickPSF** [psforever/PSF-LoginServer#380]
When healing a backpack, it opens the Inventory.

**Comment by Fate-JH** [comment]
You can't heal a backpack.
If you can get the backpack into a state where the med app is expending repair juice, then that is an issue.
If you want me to not open the inventory if the player is using a tool when interacting with the backpack, I can do that.

**Comment by NickPSF** [comment]
> If you want me to not open the inventory if the player is using a tool when interacting with the backpack, I can do that.

Yeah, I think we need a pass on all objects for this. I recall being able to do this on various objects like the Generator Terminal and others.

**Comment by NickPSF** [comment]
Fixed on wanton_use-75f503d6db
