### ISSUE TITLE
Vehicle - Enter/Exit - You cannot get out of a Vehicle if the driver has disconnected

### ISSUE THREAD

**Issue by NickPSF** [psforever/PSF-LoginServer#381]
You cannot get out of a Vehicle if the driver has disconnected.

**Comment by Fate-JH** [comment]
Can not replicate this on my local build by following obvious steps and the execution path on the Live server looks to be essentially the same.  I would need clarification to continue.

I did notice that the vehicle, after the driver departed the server, switched over to one of its slightly damaged states (smoking from the back; brake lights flickering) and it corrected itself after my other character took the driver seat.

**Comment by Mazo** [comment]
Possibly fixed at part of #420. If the vehicle had some (small) amount of velocity before disconnect players may not be able to dismount as the vehicle is still considered moving, even if only a small amount.

**Comment by Mazo** [comment]
Closing as this hasn't come up again
