### ISSUE TITLE
Vehicles - Repairing Vehicles - Vehicles sometimes get in a state where they cannot be repaired, despite being damaged; may be a health desync or something, because jacking the vehicle seemingly cleared the bug and gave the vehicle full health

### ISSUE THREAD

**Issue by NickPSF** [psforever/PSF-LoginServer#383]
Vehicles sometimes get in a state where they cannot be repaired, despite being damaged; may be a health desync or something, because jacking the vehicle seemingly cleared the bug and gave the vehicle full health.

**Comment by Fate-JH** [comment]
If mounting the vehicle does not update the health to full visually, then this becomes an issue.  As it is, it sounds just a harmless client desync.  If I knew of hover text that told would-be engineers that the object doesn't need fixing, I'd give you that.

**Comment by NickPSF** [comment]
This was reproduced recently on the 51200 server

**Comment by Mazo** [comment]
If this happens again check with advanced targetting what the health of the vehicle is before / after jacking it

**Comment by NickPSF** [comment]
https://streamable.com/hhe2kz

https://streamable.com/bqhhmh

Health stayed the same, but I think I've seen it jump before. See videos (specifically video 2)
