### ISSUE TITLE
Server Select - Server Name - World Server - The name of the World Server is not called "PSForever" as expected

### ISSUE THREAD

**Issue by NickPSF** [psforever/PSF-LoginServer#384]
The name of the World Server is not called "PSForever" as expected.

**Comment by Mazo** [comment]
https://github.com/psforever/PSF-ServerCI/blob/aaefb42e79091cbdcedb9eeaa0d140989bd84631/check.js#L384

Perhaps a special case in here to check if the branch is master, if so set the name to PSForever?

**Comment by NickPSF** [comment]
Still occurring

**Comment by NickPSF** [comment]
@pschord Anything we can do here?

**Comment by Mazo** [comment]
![image](https://user-images.githubusercontent.com/809719/82123012-f03e8200-978e-11ea-9f60-f88027308617.png)

Resolved
