### ISSUE TITLE
Vehicle Terminal - Vehicles - After confirming a Vehicle purchase at a Vehicle Terminal, your character can move as far away as they want from the Terminal before being moved into the newly spawned and purchased Vehicle 

### ISSUE THREAD

**Issue by NickPSF** [psforever/PSF-LoginServer#388]
After confirming a Vehicle purchase at a Vehicle Terminal, your character can move as far away as they want from the Terminal before being moved into the newly spawned and purchased Vehicle.

The expected behavior is that if you move too far away, you are removed from the vehicle creation queue, and your order is cancelled.

Relevant string:

`@SVCP_RemovedFromVehicleQueue_MovedTooFar=You were removed from the vehicle creation queue - you moved too far away from the creation pad.`

**Comment by Fate-JH** [comment]
So, how far away is a buyer permitted to stray from the terminal?

**Comment by NickPSF** [comment]
Unlimited range, it seems.

**Comment by Fate-JH** [comment]
So, this is not actually a problem?

**Comment by NickPSF** [comment]
It is, see string: 

`@SVCP_RemovedFromVehicleQueue_MovedTooFar=You were removed from the vehicle creation queue - you moved too far away from the creation pad.`

There's other cases, too.

```
@SVCP_Killed_OnPadOnCreate=You were killed because you were on the creation pad when a vehicle was constructing - stay clear of the pad.
@SVCP_Killed_TooCloseToPadOnCreate=You were killed because you were within %1 m's of the creation pad when a vehicle was constructing - stay clear of the pad.
@SVCP_RemovedFromVehicleQueue_Generic=You were removed from the vehicle creation queue.
@SVCP_RemovedFromVehicleQueue_ArmorChanged=You were removed from the vehicle creation queue - your current armor cannot drive the vehicle you wanted to purchase.
@SVCP_RemovedFromVehicleQueue_CaptureFlag=You were removed from the vehicle creation queue - you acquired the LLU.
@SVCP_RemovedFromVehicleQueue_VanuModule=You were removed from the vehicle creation queue - you acquired a Vanu Module.
@SVCP_RemovedFromVehicleQueue_MonolithUnit=You were removed from the vehicle creation queue - you acquired a Monolith Unit.
@SVCP_RemovedFromVehicleQueue_Destroyed=You were removed from the vehicle creation queue - you were killed.
@SVCP_RemovedFromVehicleQueue_ParentChanged=You were removed from the vehicle creation queue - you got into another vehicle.
@SVCP_RemovedFromVehicleQueue_InstantAction=You were removed from the vehicle creation queue - you chose instant action.
@SVCP_RemovedFromVehicleQueue_Quit=You were removed from the vehicle creation queue - you chose quit.
@SVCP_RemovedFromVehicleQueue_Recall=You were removed from the vehicle creation queue - you chose recall to sanctuary.
@SVCP_RemovedFromVehicleQueue_OutfitRecall=You were removed from the vehicle creation queue - you chose recall to outfit base.
@SVCP_RemovedFromQueue_TerminalDestroyed=You were removed from the vehicle creation queue - the terminal was destroyed.
```

**Comment by Fate-JH** [comment]
You know what: to heck with it.
I'll just pick a number.
3.
3's a good number.

**Comment by NickPSF** [comment]
> You know what: to heck with it.
> I'll just pick a number.
> 3.
> 3's a good number.

I'd do 5 meters, it's the max distance to use the Vehicle Terminal

**Comment by Mazo** [comment]
From memory, you could get just about off the side of the pad before it would remove you. Having it at the use distance is probably a bit too small if you consider back on live when large groups of people would all be at the terminal, some would be sitting way off to the sides out of the way of the terminal and still be seated properly.

**Comment by ScrawnyRonnie** [comment]
At a Bio Lab you could hide in the base wall stairs to avoid the inevitable OS when the queue was very long so that's gotta be in range :)

![image](https://user-images.githubusercontent.com/73139382/116240683-1952eb00-a732-11eb-9972-5c5bd8e7f85d.png)

**Comment by Fate-JH** [comment]
After spending some time with preliminary setup for this sort of renovation, I have come to the conclusion that this is a significant adjustment to the `VehicleSpawnPad` process and will not be performing such a feature change as part of the existing PR #797 as I had originally planned.
