### ISSUE TITLE
Advanced Hacking - Hacking Times - The time for hacking things with Expert Hacking is too long

### ISSUE THREAD

**Issue by NickPSF** [psforever/PSF-LoginServer#398]
The time for hacking things with Expert Hacking is too long.

**Expected Results**:

> add_property remote_electronics_kit hack_accesslocker_app_sec 0 10 5 3
> add_property remote_electronics_kit hack_accesslocker_eff_sec 0 30 60 90
> add_property remote_electronics_kit hack_accessmedicalterminal_app_sec 5 3 1 1
> add_property remote_electronics_kit hack_accessmedicalterminal_eff_sec 30 60 120 150
> add_property remote_electronics_kit hack_accessterminal_app_sec 0 10 5 3
> add_property remote_electronics_kit hack_accessterminal_eff_sec 0 30 60 90
> add_property remote_electronics_kit hack_boost_pain_app_sec 0 0 0 60
> add_property remote_electronics_kit hack_boost_pain_eff_sec 0 0 0 1800
> add_property remote_electronics_kit hack_capturebase_app_sec 60 40 20 15
> add_property remote_electronics_kit hack_disableiff_app_sec 5 3 1 1
> add_property remote_electronics_kit hack_disableiff_eff_sec 60 180 300 360
> add_property remote_electronics_kit hack_enableiff_app_sec 5 3 1 1
> add_property remote_electronics_kit hack_purgevirus_app_sec 0 0 0 3
> add_property remote_electronics_kit hack_upgradeshieldgenerator_app_sec 0 0 0 20

**Video:** https://streamable.com/9om47w

**Comment by Mazo** [comment]
Fixed in #402
