### ISSUE TITLE
Choose database solution for the LoginServer

### ISSUE THREAD

**Issue by pschord** [psforever/PSF-LoginServer#4]
Some candidates:
* MongoDB
* CouchDB
* MySQL
* Flat file
* ...

It seems like NoSQL / document based DB would allow me to move fast and use plain ol' JSON. A SQL based DB would probably be overkill unless that's preferred for account records. More transient data, such as game state may benefit more from a NoSQL solution.

**Comment by pschord** [comment]
A document based storage initially may greatly simply things. A SQL based solution would be more familiar, but having to create a fixed schema upfront would slow development.

**Comment by Brandy-92** [comment]
In my opinion a document based storage will speed up development and allow results to be shown to the community/others quicker, not to mention the motivational boost of getting things working. Things can always be reworked for greater security etc.

**Comment by Flosus** [comment]
On the other hand: SQL is "more common". Many people use it and it gets taught in school. So people could get easier into the project.

**Comment by pschord** [comment]
I like the SQL is more common argument - everything in this project so far is very *uncommon*. Plus, SQL is easy to read and the schema is self documenting.

My argument against SQL is that I have to spend a lot of time thinking about a database schema and less time just throwing data in to a database. At the moment, I have no idea what my schema is going to be for many things as a lot isn't done. So I have the choice of rewriting the schema all the time or just shoving data in to the DB when I need to.

Still, I'm not 100% sold on NoSQL solutions and I'm still open to suggestions.

**Comment by Flosus** [comment]
Well, I can't tell tell you the pro or cons of NoSQL-DBs, because i haven't used them jet. What i can do is drawing some diagrams, if i have an SQL schema. (And of curse help with the schema itself, when i can contribute something)

**Comment by W-M-D** [comment]
Document based ftw

**Comment by Flosus** [comment]
@W-M-D Wow, that's a very substantiated answer...

**Comment by pschord** [comment]
Having done more research I am now afraid of using a document based model or in general a NoSQL solution.

Read this real experience through and through: http://www.sarahmei.com/blog/2013/11/11/why-you-should-never-use-mongodb/

The gist is that as a project their problems didn't seem relational and one day they realized they needed to be able to do relational queries. PlanetSide was designed before NoSQL was a thing, therefore all of the data will be designed with a relational database in mind. This and people's familiarity is probably reason enough to with something safe and well understood like, PostgreSQL.

Document based "sounds" cool and hey it's something new, but it might be _too_ new for this project.

My argument earlier 

> My argument against SQL is that I have to spend a lot of time thinking about a database schema and less time just throwing data in to a database. At the moment, I have no idea what my schema is going to be for many things as a lot isn't done. So I have the choice of rewriting the schema all the time or just shoving data in to the DB when I need to.

Doesn't really hold up against these issues. It's not like our data is going to be changing all the time. It's not a moving target - PlanetSide is not under development. If we need to add a column, it's as simple as just dropping the existing table and creating a new one (or altering). 

There might be a place for NoSQL in this project - unstructured logs for instance - but for game data, it's less clear.

**Comment by SouNourS** [comment]
I can only vote for MySQL because it's the only DB I know. ^_^

**Comment by Crazer94** [comment]
As SouNourS said, I also say MySQL since I have worked with it before and generally know it.

**Comment by Shadow41190** [comment]
so I know I am kind of new around here. but I too, vote MySQL.

**Comment by Flosus** [comment]
@SouNourS , @Crazer94 and @Shadow41190 take a look at [MariaDB](https://en.wikipedia.org/wiki/MariaDB). It's a fork of MySQL without the _Oracle_ in it.

**Comment by pschord** [comment]
So I didn't realize that PostgreSQL's datatypes are very different from MySQL. MariaDB is looking better as it's more free and under more active development. I think we just need to choose _something_ and see how it works for us.

**Comment by Ness199X** [comment]
NoSQL is "hip" and a lot of people use it because it's "hip". But look at any MMO emulator, and it uses SQL. Look at most any live MMO, and it uses SQL. MySQL or MariaDB are tried and true solutions to the sort of problem's this project is going to have, and a lot of people are familiar with them. Just my two cents.

**Comment by SouNourS** [comment]
@Flosus, true, mariadb looks better :)

**Comment by pschord** [comment]
Okay lets end this discussion here then.
MariaDB / MySQL it is (they seem to be quite compatible)
Will keep issue open for another week and close it if there aren't any other comments.
