### ISSUE TITLE
Vehicles - Vehicle Acquisition - Vehicle Pad - Vehicle Wreckage is not manually cleared from the Vehicle Pad when attempting to acquire a vehicle, requiring players to manually use a command to do so

### ISSUE THREAD

**Issue by NickPSF** [psforever/PSF-LoginServer#407]
Vehicle Wreckage is not manually cleared from the Vehicle Pad when attempting to acquire a vehicle, requiring players to manually use a command to do so.

**Expected Result:** The server should take care of this clean up on it's own.

**Comment by Fate-JH** [comment]
About this issue, when you're talking about "vehicle wreckage" that must be cleared by "using a command", you very specifically mean the wreckage of a previously spawned vehicle that is blocking other spawning jobs?
