### ISSUE TITLE
Repair/Rearm Silos - Landing Pads - Vehicle Repair Terminals - The repair rate of Vehicle Repair Terminals seems to be too high, making it extremely hard to kill Vehicles camping these Terminals 

### ISSUE THREAD

**Issue by NickPSF** [psforever/PSF-LoginServer#408]
The repair rate of Vehicle Repair Terminals seems to be too high, making it extremely hard to kill Vehicles camping these Terminals.

**Comment by Mazo** [comment]
If I remember right taking damage would stop the repair for a while, wouldn't it? I think that's probably the root cause of it feeling unbalanced.

**Comment by NickPSF** [comment]
That could very well be, but I'm not sure.
