### ISSUE TITLE
Vehicles need preventative measures to stop them from driving underwater

### ISSUE THREAD

**Issue by NickPSF** [psforever/PSF-LoginServer#409]
Vehicles do not have any mechanism to prevent them from driving under water.

https://streamable.com/82w7k8

**Comment by Mazo** [comment]
This is something that needs the server to have the entire map data loaded to work out as the client emits no indication a vehicle is underwater. I suggest we close this for the time being and leave it on the "to do feature backlog" as there's really nothing we can do about it right now. @NickPSF

**Comment by Fate-JH** [comment]
Technically, I can't say offhand if any facility basements are below sea level.  If all of them keep your head above water, then all I'd need is the water level for a given zone to start people drowning below a certain z-coord.

**Comment by Fate-JH** [comment]
Vehicles can and will become disabled through the application of too much water on most major continents.  I will effectively consider this closed.
