### ISSUE TITLE
Damage - All players became immune to damage during a playtest

### ISSUE THREAD

**Issue by NickPSF** [psforever/PSF-LoginServer#411]
All players became immune to damage during a playtest.

Edit: As a note, /suicide and Implants were also not working for affected characters. New characters/dead characters who spawned in were able to be damaged, it seemed. Switching zones cleared the issue.

Video: https://streamable.com/m97y56

**Comment by NickPSF** [comment]
As a note, /suicide and Implants were also not working for affected characters. New characters/dead characters who spawned in were able to be damaged, it seemed. Switching zones cleared the issue.

**Comment by Fate-JH** [comment]
A simultaneous failure of the `PlayerControl` entity of every player connected to a zone at a certain time?  Sounds like fun to debug.

**Comment by NickPSF** [comment]
Haven't seen this for a long while. Closing.
