### ISSUE TITLE
Character Sync - Death - Movement - Players with a high ping/loss may be able to control their characters after death (corpse moving while dead) 

### ISSUE THREAD

**Issue by NickPSF** [psforever/PSF-LoginServer#412]
Players with a high ping/loss may be able to control their characters after death (corpse moving while dead).

**Comment by SouNourS** [comment]
I guess it's because their client doesn't know they're dead?

**Comment by Fate-JH** [comment]
Once I did block movement input where a character was considered dead on the server ...

**Comment by jgillich** [comment]
This is *probably* fixed now.
