### ISSUE TITLE
Loading - When initially loading into a zone on a fresh session, there is sometimes a load screen bug, with or without accompanying disconnect popup

### ISSUE THREAD

**Issue by NickPSF** [psforever/PSF-LoginServer#413]
When initially loading into a zone on a fresh session, there is sometimes a load screen bug, with or without accompanying disconnect popup.

Usually reconnecting fixes this issue without problem.

**Comment by jgillich** [comment]
What's the status on this @NickPSF? Sounds like it's related to networking so probably long fixed

**Comment by NickPSF** [comment]
Cannot reproduce
