### ISSUE TITLE
Quit Command - Logging in a different character - When quitting back to Character Select and choosing a different character (different faction?), the game will crash to desktop

### ISSUE THREAD

**Issue by NickPSF** [psforever/PSF-LoginServer#414]
When quitting back to Character Select and choosing a different character (different faction?), the game will crash to desktop.

**Comment by Mazo** [comment]
Can't replicate locally or on master. Works fine for me.

**Comment by NickPSF** [comment]
https://streamable.com/nworoo

Typically higher repro than normal /zone crashing, it's almost guaranteed when swapping characters from my history. Have seen it many times.

**Comment by Mazo** [comment]
That last character was on old oshur. I wouldn't be surprised if weird things happened there.

Does this happen with any other continent when changing characters?

**Comment by NickPSF** [comment]
Yeah it does, this has been around for a long time. Load screen CTD happens much, much more frequently when returning to character select and then logging back in with a character.

**Comment by ScrawnyRonnie** [comment]
Tested what is shown in the video about a dozen times across that many chars and all empires and could not reproduce. Fixed/close?

**Comment by Fate-JH** [comment]
Assuming fixed when quit/ instant action, and recall were properly implemented.
