### ISSUE TITLE
Characters with the same name can be created!

### ISSUE THREAD

**Issue by pschord** [psforever/PSF-LoginServer#435]
Culprit: https://github.com/psforever/PSF-LoginServer/blob/42a2512aa010be16d542ebda5e362ba6be9b9650/pslogin/src/main/scala/WorldSessionActor.scala#L3672

![image](https://user-images.githubusercontent.com/14133344/81975437-057fa900-95f5-11ea-8528-54d793fdee79.png)

**Comment by Fate-JH** [comment]
The database should be the one failing this, not the server.

I'll grant you that this is definitely not vanilla.  Allowing it, on top of that, would mean that we can not rely on name tests to confirm that any two players are unique and instead must use CharId.  We should always be using CharId anyway.  It will always be unique as it is assigned by the database on character creation.

**Comment by Mazo** [comment]
We definitely aren't though, for example Deployables or Vehicles use `OwnerName`

**Comment by Fate-JH** [comment]
Predates proper `CharId`.  Also `OwnerName` serves a specific purpose - connecting ownership across characters and, where available, when returning to a zone.  Currently, it only applies to deployables.

**Comment by jgillich** [comment]
This is fixed by #508
