### ISSUE TITLE
Wall Turret - Base Hacking -  Being in a turret whilst a facility gets hacked kicks you out, but it thinks you're still in the turret with insane damage potential

### ISSUE THREAD

**Issue by NickPSF** [psforever/PSF-LoginServer#439]
Being in a turret whilst a facility gets hacked kicks you out, but it thinks you're still in the turret with insane damage potential.

**Comment by Fate-JH** [comment]
Hacking a facility or tower while someone is in a turret does kick the player in the turret out of the turret locally.  The game will not fire any packets indicating the kick.  This situation must be tested explicitly.

**Comment by Fate-JH** [comment]
Just to confirm: this is "during a facility hack," not "when the facility hack completes," correct?

**Comment by Mazo** [comment]
Correct, as soon as the control console is hacked turrets become unavailable

**Comment by Mazo** [comment]
Needs regression testing on 51000

**Comment by Mazo** [comment]
Was fixed in #443
