### ISSUE TITLE
Wall Turret - Turret Upgrading - Upgrading a turret as someone gets in gets you stuck upgrading with no option but /suicide

### ISSUE THREAD

**Issue by NickPSF** [psforever/PSF-LoginServer#440]
Upgrading a turret as someone gets in gets you stuck upgrading with no option but /suicide.

Edit: The turret did already have an upgrade, might be relevant

**Comment by NickPSF** [comment]
The turret did already have an upgrade, might be relevant

**Comment by ScrawnyRonnie** [comment]
Still around and happens with un-upgraded turrets too (regular wall turrets). Aside from /suicide to "snap out of it", taking damage also gets you unstuck. Interestingly, if the player jumps out of the turret while you are stuck, it will return you to the menu where you select which type of upgrade to start or you can cancel out of it.
