### ISSUE TITLE
UI - Caverns - Base Hacking - The flag icon that denotes a Facility has been hacked does not show up on the map when Cavern Facilities are hacked

### ISSUE THREAD

**Issue by NickPSF** [psforever/PSF-LoginServer#448]
The flag icon that denotes a Facility has been hacked does not show up on the map when Cavern Facilities are hacked.

I remember this occurring on 51200 but was fixed.

**Comment by Mazo** [comment]
After a quick test the flag does show if you log out and back in, so something is missing to send the map update when the CC is first hacked
