### ISSUE TITLE
Caverns - GM Commands - !hack - When using !hack <faction> in the Caverns, all buildings change ownership, despite being neutral buildings (similar to how this occurred with Bridges/Bunkers on surface)

### ISSUE THREAD

**Issue by NickPSF** [psforever/PSF-LoginServer#449]
When using !hack <faction> in the Caverns, all buildings change ownership, despite being neutral buildings (similar to how this occurred with Bridges/Bunkers on surface).

**Comment by Mazo** [comment]
Fixed in #503
