### ISSUE TITLE
GM Commands - !hack - Helheim - Using !hack Helheim on Esamir does not work

### ISSUE THREAD

**Issue by NickPSF** [psforever/PSF-LoginServer#450]
Using !hack Helheim on Esamir does not work.

**Comment by Mazo** [comment]
Fun fact, the base is named `Helhiem` in the mpo file.

![](https://media2.giphy.com/media/kyrd72DC2Iwfu/giphy.gif?cid=ecf05e4708455a75d35284dadcfbf2f0032a57d87d4ed4c5&rid=giphy.gif)

**Comment by Mazo** [comment]
I'm not entirely convinced that we should modify the server to fix this and add in a special case just for it, after all Helhiem seems to be the correct name, and Helheim that is shown on the client side seems to be the error from looking at the game files.

Perhaps we should park this until we have client patching?

**Comment by SouNourS** [comment]
> I'm not entirely convinced that we should modify the server to fix this

You can modify your script O:-)
LOL
