### ISSUE TITLE
Damage - Splash - In some instances, splash damage does way less damage than intended

### ISSUE THREAD

**Issue by NickPSF** [psforever/PSF-LoginServer#452]
In some instances, splash damage does way less damage than intended. This is most noticeable and reported with Reaver and Decimator rockets (as they are frequently used).

- Splash damage only does Armor damage?
- Sometimes point blank splash damage doesn't even register.

Will update this ticket with more info.

**Comment by Fate-JH** [comment]
I mentioned in some PR (was it my destruction PR) that, during testing, the secondary fire of the Beamer seemed to only be doing armor damage and I was uncertain if that was correct.  No one seemed to care.

**Comment by Mazo** [comment]
```
8400:add_property beamer firemode0_add_damage0 4
8401:add_property beamer firemode0_add_damage1 -1
8402:add_property beamer firemode0_add_damage2 -1
8403:add_property beamer firemode0_add_damage3 -1
8404:add_property beamer firemode0_add_damage4 -1

8414:add_property beamer firemode1_add_damage0 -3
8415:add_property beamer firemode1_add_damage1 -3
8416:add_property beamer firemode1_add_damage2 -3
8417:add_property beamer firemode1_add_damage3 -3
8418:add_property beamer firemode1_add_damage4 -3
```

I feel like something isn't right there, even still. Beamer shouldn't be splash damage?

**Comment by NickPSF** [comment]
The Beamer secondary fire mode might only do Armor damage depending on what armor they are shooting because of the low direct damage and damage resistance of the armor is high enough to prevent health damage.

**Comment by NickPSF** [comment]
I believe this was looked at when Fate adjusted splash damage
