### ISSUE TITLE
The damage_multiplier property does not function for the Galaxy Gunship and other objects

### ISSUE THREAD

**Issue by NickPSF** [psforever/PSF-LoginServer#455]
The `damage_multiplier` property used for the Galaxy Gunship does not function for objects.

```
add_property galaxy_gunship damage_multiplier 0.63
```

Galaxy Gunships should only receive 63% of incoming damage.

**Comment by Mazo** [comment]
Glancing at the code we have a `GalaxyGunshipReduction` damage modifier now, closing this out.
