### ISSUE TITLE
Spectators should not be included in empire populations on the admin portal

### ISSUE THREAD

**Issue by Mazo** [psforever/PSF-LoginServer#457]
Or perhaps not in the player list at all. Avoids factions looking more populated than they actually are.

**Comment by NickPSF** [comment]
Agreed, should be same for /who and population bars in-game as well

**Comment by pschord** [comment]
Feel free to modify https://github.com/psforever/PSF-LoginServer/blob/270485fa4def5bd7d581aa3a0670659746e91e66/common/src/main/scala/net/psforever/objects/zones/InterstellarCluster.scala#L67-L76
We could send the whole player object or just filter on spectators.
