### ISSUE TITLE
Players can be in state where they are firing, but not visibly firing on other clients.

### ISSUE THREAD

**Issue by Mazo** [psforever/PSF-LoginServer#460]
After reports of liberator bombs not showing up sometimes, and seeing it happen to ArsheeTV at 1:08:20 on https://www.twitch.tv/videos/627207457 I did a bit of digging.

It turns out this affects all weapons, not just liberator bombs. If you empty a clip, and continue to keep attempting to fire resulting in `WeaponDryFireMessage`, then immediately reload you will get the result seen in the following video: https://streamable.com/11dftx

If you wait a small amount of time after the last `WeaponDryFireMessage` before reloading the issue won't occur.

**Comment by NickPSF** [comment]
Nice find

**Comment by Mazo** [comment]
On further digging, I've noticed that the dry fire noise plays AFTER reloading for other players. That's likely the source of the issue since other clients think the weapon is empty.

**Comment by Mazo** [comment]
Confirmed, a stray `WeaponDryFireMessage` is received after `ReloadMessage`. PR incoming.
