### ISSUE TITLE
Engineering Cert Lines - Repairing - Engineering Cert Lines starting at Combat Engineering do not benefit from increased Repair values

### ISSUE THREAD

**Issue by NickPSF** [psforever/PSF-LoginServer#464]
Engineering Cert Lines starting at Combat Engineering do not benefit from increased Repair values.

**Engineering**

- BANK: 12 per tick (1.0x)
- Nano Dispenser: 32 per tick (1.0x)

**Combat Engineering**

- BANK: 14 per tick (1.2x)
- Nano Dispenser: 48 per tick (1.5x)

**Assault, Fortification, and Advanced Engineering**

- BANK: 18 per tick (1.5x)
- Nano Dispenser: 64 per tick (2x)

**Comment by Fate-JH** [comment]
Based on what I can tell, you're currently getting a flat rate of 20 repair per application and sometimes 40 for some things.  The 20 is lower than the reported base gluegun rate of 32 but faster than the BANK rate at any certification; 40 is halfsies between the the basic Engineering rate for the gluegun and its next rank.  This is related to fire mode "add" values on the gluegun.

To cut a long story short, if I fix this for the BANK, I will not tolerate complaint that the BANK feels like it's been nerfed, or that the gluegun feels like it's been unchanged.
