### ISSUE TITLE
Air Vehicles - Gunner Seat - Bailing - It is impossible to bail from an Aircraft Gunner Seat position while the Aircraft is in motion

### ISSUE THREAD

**Issue by NickPSF** [psforever/PSF-LoginServer#474]
It is impossible to bail from an Aircraft Gunner Seat position while the Aircraft is in motion.

Affects:

- Galaxy
- Galaxy Gunship
- Liberator
- Vulture

**Comment by Mazo** [comment]
I think this is due to some seats not having `Bailable` set, though I can't think of any case where a seat that is **not** the driver is not allowed to bail, excluding the usual damaged mechanism on low health.

It may be easier to just allow any seat other than the driver's to bail?

**Comment by Mazo** [comment]
Fixed in #685
