### ISSUE TITLE
!hack <faction> does not completely hack all of the buildings in a Caverns Zone

### ISSUE THREAD

**Issue by NickPSF** [psforever/PSF-LoginServer#482]
!hack <faction> does not completely hack all of the buildings in a Caverns Zone

**Comment by Mazo** [comment]
Seems fine on 61000 after #484

**Comment by NickPSF** [comment]
@Mazo Still occurring in Adlivun (c3) for both AT Plants.

**Comment by Mazo** [comment]
Resolved
