### ISSUE TITLE
Player can spawn at hostile base if it changes owner during the spawn timer

### ISSUE THREAD

**Issue by jgillich** [psforever/PSF-LoginServer#487]
Pretty minor, but:

* Player selects friendly base to spawn at
* Hack completes, base changes faction
* Player still spawns at the now hostile base

**Comment by Mazo** [comment]
I'm pretty sure you can spawn at a just destroyed AMS too

**Comment by NickPSF** [comment]
This can also happen if the generator/spawn tubes are downed after spawn has been set, instead of sending you to another base.
