### ISSUE TITLE
Trunks - Vehicle trunks, particularly on large vehicles such as the Galaxy Gunship, need a slightly less aggressive auto-close range

### ISSUE THREAD

**Issue by NickPSF** [psforever/PSF-LoginServer#488]
Vehicle trunks, particularly on large vehicles such as the Galaxy Gunship, need a slightly less aggressive auto-close range.

Most noticeable on stuff like Galaxy Gunship.

**Comment by Mazo** [comment]
Perhaps a valid reason to implement the `trunklocation` property into the server, and offset the distance check by the distance to the trunk.
