### ISSUE TITLE
Picking a new SQL library

### ISSUE THREAD

**Issue by jgillich** [psforever/PSF-LoginServer#493]
I did some research on the best options for a new Postgres library, here they are:

## doobie

> doobie is a pure functional JDBC layer for Scala and Cats. It is not an ORM, nor is it a relational algebra; it simply provides a functional way to construct programs (and higher-level libraries) that use JDBC. For common use cases doobie provides a minimal but expressive high-level API

* Website: https://tpolecat.github.io/doobie/
* Github stars: 1.7k
* Async: Yes
* Type safe: No
* Magic(TM): No

### Example
```scala
case class Country(code: String, name: String, population: Long)

def find(n: String): ConnectionIO[Option[Country]] =
  sql"select code, name, population from country where name = $n".query[Country].option
```

### Pros/Cons

\+/\- No magic

\+ Functional

\+ Popular

### What people say about doobie

> We have one service that used slick and it was very painful so we used doobie for everything since and have no regrets at all. Code complexity and boilerplate is far lower, you can pick your monad and you can use actual SQL.

> Although Doobie makes writing SQL less of a trainweck, doing so is still a PITA.

> Doobie is awesome but, in my experience, I had to write a large handful of helper functions to make it truly easy to use.

## Quill

> Quill provides a Quoted Domain Specific Language (QDSL) to express queries in Scala and execute them in a target language. The library’s core is designed to support multiple target languages, currently featuring specializations for Structured Query Language (SQL) and Cassandra Query Language (CQL).
> 
> 1. **Boilerplate-free mapping**: The database schema is mapped using simple case classes.
> 2. **Quoted DSL**: Queries are defined inside a `quote` block. Quill parses each quoted block of code (quotation) at compile time and translates them to an internal Abstract Syntax Tree (AST)
> 3. **Compile-time query generation**: The `ctx.run` call reads the quotation's AST and translates it to the target language at compile time, emitting the query string as a compilation message. As the query string is known at compile time, the runtime overhead is very low and similar to using the database driver directly.
> 4. **Compile-time query validation**: If configured, the query is verified against the database at compile time and the compilation fails if it is not valid. The query validation **does not** alter the database state.

* Website: https://getquill.io/#docs
* Github stars: 1.7k
* Async: [Yes](https://getquill.io/#contexts-quill-async)
* Type safe: Yes
* Magic(TM): Yes

### Example
```scala
case class Person(id: Int, name: String, age: Int)
case class Contact(personId: Int, phone: String)

val q = quote {
  for {
    p <- query[Person] if(p.id == 999)
    c <- query[Contact] if(c.personId == p.id)
  } yield {
    (p.name, c.phone)
  }
}

ctx.run(q)
// SELECT p.name, c.phone FROM Person p, Contact c WHERE (p.id = 999) AND (c.personId = p.id)
```

### Pros/Cons

\+/\- It's magic

\+ Compile time query validation

\+ Popular

### What people say about Quill

> I've used Quill on a number of projects recently because of it's support for Async Postgres. Overall very satisfied with it.

> We have switched from Slick to Quill and I would advise you to stay away from it. Quill is nice when it works but when it doesn't you're in a world of hurt.

# ScalikeJDBC

> ScalikeJDBC is a tidy SQL-based DB access library for Scala developers. This library naturally wraps JDBC APIs and provides you easy-to-use and very flexible APIs. What’s more, QueryDSL makes your code type-safe and reusable.

* Website: http://scalikejdbc.org/
* Github stars: 1.1k
* Async: [Not production ready](https://github.com/scalikejdbc/scalikejdbc-async)
* Type safe: Yes
* Magic(TM): No

### Example
```scala
case class Member(id: Long, name: Option[String], createdAt: ZonedDateTime)
object Member extends SQLSyntaxSupport[Member] {
  override val tableName = "members"
  def apply(rs: WrappedResultSet) = new Member(
    rs.long("id"), rs.stringOpt("name"), rs.zonedDateTime("created_at"))
}

// find all members
val members: List[Member] = sql"select * from members".map(rs => Member(rs)).list.apply()
```

### Pros/Cons

\+/\- No magic

\- Async support is in alpha

### What people say about ScalikeJDBC

Unfortunately, they don't say much.

## Other Options

* [Skunk](https://tpolecat.github.io/skunk/), new library from the doobie author, but marked as pre-release.
* [Slick](http://scala-slick.org/), formerly one of the most popular libraries, now [mostly dead](https://www.reddit.com/r/scala/comments/dvnywd/is_slick_dead/).
* [jOOQ](https://www.jooq.org/), more of a Java-native library.

## Resources

* [Comparing Scala relational database access libraries](https://softwaremill.com/comparing-scala-relational-database-access-libraries/)
* [Database access libraries in Scala](https://medium.com/@takezoe/database-access-libraries-in-scala-7aa7590aa3db)
* [Reddit: Doobie vs Quill](https://www.reddit.com/r/scala/comments/9ytbih/doobie_vs_quill_which_do_you_prefer/)
* [Reddit: Moving away from Slick?](https://www.reddit.com/r/scala/comments/gnsys3/moving_away_from_slick/)
* [Quill compared to Slick](https://github.com/getquill/quill/blob/master/SLICK.md) - [Reddit Discussion](https://www.reddit.com/r/scala/comments/3v3vy0/comparison_between_quill_and_slick_for_database/)

**Comment by jgillich** [comment]
Something interesting to note is that people don't always mean the same thing when they use the words async. doobie is async in the sense that blocking operations run on a dedicated thread pool, and the same applies to Quill. That's why the doobie author made [Skunk](https://tpolecat.github.io/skunk/index.html), which is completely non-blocking similar to postgres-async. Interesting talk on the topic: https://www.youtube.com/watch?v=NJrgj1vQeAI

**Comment by Mazo** [comment]
At first doobie jumped out at me and being simple and quick to implement, but looking into Quill further it does seem to also make a lot of sense, it comes across to me as being essentially the Java/Scala version of Entity Framework + LINQ, great for most use cases but can quickly turn into a headache for more complex use cases.

Fortunately, I don't think we'll really be one of those complex use cases. Most if not all of our queries should be quite straight forward, and most bits of data we'll need to save/retrieve are fairly isolated from each other.

Tying whichever option we pick into our Actors is going to be the key part though, in a sane and async way (Futures? Message callbacks?).  But regardless, I'm going to go with Quill as my primary choice, and doobie secondary.

**Comment by jgillich** [comment]
Yea I think Entity Framework is an apt comparison, and I've had mostly positive experiences with EF so I'm also leaning towards Quill, although I wouldn't mind doobie either. But I think that settles it then (unless @Fate-JH has any objections).

I'll take a deeper dive into Quill and get a prototype going. If any unforeseen issues arise we can always reconsider.
