### ISSUE TITLE
Integrate MariaDB connector in to the server

### ISSUE THREAD

**Issue by pschord** [psforever/PSF-LoginServer#50]
We have settled on MariaDB for our database. This is essentially feature equivalent with MySQL but more open source (different philosophy).

Now we need
- A Scala library that works well with MariaDB / MySQL. We DO NOT want a typesafe super-scala crazyness library as it will probably be much harder to read and our SQL will not be portable
- An understanding of how JDBC fits in to all of this
- Some schemas to start building (login session, world session, world list, character table, world state)

**Comment by Flosus** [comment]
Should the schemas be in a liquibase formatted sql?

This would allow us to automate sql updates.

If you don't know liquibase: http://www.liquibase.org/

**Comment by SouNourS** [comment]
https://downloads.mariadb.org/connector-java/

https://mariadb.com/kb/en/mariadb/about-mariadb-connector-j/

http://manuel.bernhardt.io/2014/02/04/a-quick-tour-of-relational-database-access-with-scala/

**Comment by pschord** [comment]
Work has begun on accounts database in #103
