### ISSUE TITLE
Complete abstraction for PlanetSide message channels

### ISSUE THREAD

**Issue by pschord** [psforever/PSF-LoginServer#51]
PlanetSide runs on top of UDP. UDP is not reliable.

We want a nice way for the user to send messages to a client with some reliability guarantees without worrying about how to construct a SlottedMetaPacket. We should completely abstract away from fragmentation issues, packet reordering, and packet loss.

Code needs to be written to correctly these cases if we are going to have a reliable server.
This is related to #3

**Comment by pschord** [comment]
This has been mostly handled by PacketCodingActor, but we are still missing some details like resending if no response from client, resending a resend (if the client requested one).

**Comment by jgillich** [comment]
Resolved by #582
