### ISSUE TITLE
Objects - AMS - Respawn - Sometimes objects in the world do not exist on certain player's clients, when they should (most noticeable with AMS)

### ISSUE THREAD

**Issue by NickPSF** [psforever/PSF-LoginServer#528]
Sometimes objects in the world do not exist on certain player's clients, when they should (most noticeable with AMS)

**Comment by Mazo** [comment]
This is likely down to the zoning process overloading the client. I noticed it's became significantly worse when we started bundling the zoning setup packets again, which is why that was reverted.

**Comment by ScrawnyRonnie** [comment]
Haven't seen this behavior in a long time. Probably okay to close this one out.

**Comment by Fate-JH** [comment]
Imma close it just so we could open more specific issues if need be later.
