### ISSUE TITLE
  PSF start error

### ISSUE THREAD

**Issue by spooky18** [psforever/PSF-LoginServer#620]
Hello!

    There is an error in the picture after running the command. It seems that it is a database error. 
Before upgrading the database architecture, I can deploy PSF normally. After upgrading,
 I am not familiar with the specific operation. 
You can use the README.md Is the introduction more specific and detailed? thank you!
![搜狗截图20201022215115](https://user-images.githubusercontent.com/35887910/96882063-7c2ca680-14b1-11eb-89fc-f9b2833bc53b.png)

**Comment by jgillich** [comment]
You set `game.new-avatar.br = 40` in your config, correct? That doesn't currently work because the enum only goes up to 25, try 25 instead.

**Comment by spooky18** [comment]
> 
> 
> You set `game.new-avatar.br = 40` in your config, correct? That doesn't currently work because the enum only goes up to 25, try 25 instead.

Thank you very much for solving the problem after modifying level 25. However, there are new errors. Flyway is not familiar with this tool. What specific commands are needed to repair the errors?
![搜狗截图20201023110102](https://user-images.githubusercontent.com/35887910/96951799-dc5a3180-151f-11eb-8b14-3db3b8f3b8b9.png)

**Comment by jgillich** [comment]
Start with `--baseline-on-migrate`

**Comment by spooky18** [comment]
> --baseline-on-migrate
Thank you, the problem is solved, but not with -- baseline on migrate

**Comment by jgillich** [comment]
I wasn't referring to the flyway cli but to the server itself. But I'm glad you managed to get it working!

**Comment by spooky18** [comment]
> 
> 
> I wasn't referring to the flyway cli but to the server itself. But I'm glad you managed to get it working!



I found a new problem again. There is still a problem with the database. Would you please check if the flyway in the picture is configured correctly?
![flyway](https://user-images.githubusercontent.com/35887910/96962292-12f07600-1539-11eb-9313-9c2929c658dd.png)

**Comment by jgillich** [comment]
Those are normal, pain boxes in caves are not set up correctly.

**Comment by spooky18** [comment]
> 
> 
> Those are normal, pain boxes in caves are not set up correctly.

I don't understand at all pain boxes in caves，How to do it?

**Comment by jgillich** [comment]
You don't have to do anything, this needs to be addressed by us developers. There are a lot of things that are incomplete/missing and caves are one of them. These warnings are no big deal, just ignore them.

Btw, are you the guy running the Chinese server? You'll probably want to use the `stable` branch for a production deployment since `master` has some issues at the moment.

**Comment by spooky18** [comment]
Yes, I'm the administrator of PSF in China. Brother, you are observation marvelous. You can understand Chinese in xshell.

At present, there are two problems

1: The server can't log in correctly. Please look at the picture in the screenshot again. There is an error in the database. I can't find the reason. Src / main / resources/ application.conf I configured the PostgreSQL settings correctly.

2: Which version is suitable for production?
![96962356-2ef41780-1539-11eb-8f83-405af0455678](https://user-images.githubusercontent.com/35887910/96992259-34168e00-155c-11eb-856c-81e61e1ed371.png)

**Comment by spooky18** [comment]
Stable URL I found the version you're in charge of

https://github.com/psforever/PSF-LoginServer/tree/stable


Now there are database errors, unable to log in to the game.

**Comment by jgillich** [comment]
No, your database is working fine.

* Sentry warning: Can be ignored, it simply means you aren't using Sentry (this is shown by sentry automatically and idk if we can make it not do that)
* Connection disconnected info messages: We use a pool of database connections and when they're unused they're closed. `INFO` messages are not errors. ;)
* Unable to retrieve IP address data: It happens some times and I'm not sure why, but it doesn't have serious consequences, you'll still be able to log in

The actual problem here is the packet decoding error. I rewrote a lot of the networking code recently and there are some remaining issues with that. That's why I made the `stable` branch, it's reasonably up to date but without the networking changes. It's what we're running on our server at the moment.

**Comment by spooky18** [comment]
I downloaded 616 version according to your stable version URL, but there seems to be an error. I can't log in to the server. This problem has not been encountered in the old version. How can I solve it? Is it a packet decryption library file libpscrypto.so Update? Hope you can get a reply to solve this problem.
![v612-error](https://user-images.githubusercontent.com/35887910/97396357-def2c780-1921-11eb-960d-12b07ca5ef87.png)

**Comment by spooky18** [comment]
Could you please tell me your Discord ID?

**Comment by jgillich** [comment]
> I can't log in to the server.

Meaning? What happens when you log in? Can you try another account?

**Comment by spooky18** [comment]
At present, my situation is like this: I used 4xx version to deploy the service normally, but 612 version has not been deployed normally to play games.

The biggest difference between the deployment process of 4xx and that of 612 is the database. You said that there is no problem with my database. What other problems lead to the failure to log in to the game correctly now?

The deployment process is like this

1: Install all environment dependent tools and packages

2: Set the necessary server configuration information Src / main / resources/ application.conf

3: Create, import, database schema.sql , configure the database connection in flyway

flyway-7.0.4/conf/ flyway.conf After executing. / flyway baseline, start PSF

sbt server/run
![Uploading 2.png…]()

**Comment by jgillich** [comment]
> I used 4xx version to deploy the service normally, but 612 version has not been deployed normally to play games.

I don't know what these numbers mean. What commit hash are you on?

> Set the necessary server configuration information Src / main / resources/ application.conf

It works, but you're supposed to put your config in `config/psforever.conf`

Did you try another account? If you add logs, please do the complete log in text form.

**Comment by spooky18** [comment]
> I don't know what these numbers mean. What commit hash are you on?
![#612](https://user-images.githubusercontent.com/35887910/97772087-91bf6180-1b7e-11eb-911b-7cbd0d94d14d.png)

> Did you try another account? If you add logs, please do the complete log in text form.
Other accounts can't log in after trying.
