### ISSUE TITLE
Power consumption of   #612 version power plant is too fast

### ISSUE THREAD

**Issue by spooky18** [psforever/PSF-LoginServer#648]
Power consumption of   #612 version power plant is too fast，Is the latest version fixed？
![版本](https://user-images.githubusercontent.com/35887910/102690163-83b4c580-423e-11eb-8561-9fb5b26b660c.png)
![612](https://user-images.githubusercontent.com/35887910/102690976-13a93e00-4244-11eb-9884-62f4935f8c63.png)

**Comment by jgillich** [comment]
NTU drain speed should be mostly fine now. We only have limited information and our current value is actually lower than what we believe it should be, but if you manage to get specific information on this topic let us know.
