### ISSUE TITLE
Vehicle - ANT Filling "NTU Level" Bar in HUD Doesn't Fill

### ISSUE THREAD

**Issue by ScrawnyRonnie** [psforever/PSF-LoginServer#653]
When filling an ANT at a Warpgate, the NTU Level bar at the bottom of the screen will not fill up. Scenarios tested:

1) If an ANT is pulled and driven to a Warpgate on the same continent without ever exiting the vehicle, the NTU Level bar will not fill on your screen despite the ANT actually filling up. When the ANT is full it will stop filling, but doesn't display the progress in the bar.
2) With the ANT in scenario 1, if you then use a Warpgate to zone to another continent (or even the same one you are already on by clicking on a Warpgate), the NTU Level bar will show the amount you filled it to.
3) You can also simply exit and enter the ANT that you have filled (or not yet filled) and start filling it. This corrects the display issue as well and the bar on screen fills as the ANT does.

Something about zoning and exiting/entering the vehicle again makes it show the NTU level in the display.

**Comment by NickPSF** [comment]
No longer occurring on latest
