### ISSUE TITLE
Vehicles - Rearming causes vehicle's trunk to appear empty.

### ISSUE THREAD

**Issue by ScrawnyRonnie** [psforever/PSF-LoginServer#654]
If you go to a Landing Pad with an aircraft or Repair/Rearm Silo with a ground vehicle, rearming causes the vehicle's trunk to appear empty. You are unable to reload because it thinks there is no ammo in the trunk. This happens with both one-man and vehicles that have gunners. The things listed below can temporarily correct it, but it happens again when rearming.
1) Exiting and entering the vehicle (doesn't always work).
2) Using a Warpgate to zone somewhere else.
3) Exiting the vehicle and opening the trunk, then getting back in.

**Comment by Fate-JH** [comment]
Technically all of those actions do the same thing - (attempt to) locally load all of the contents of the trunk.  When you get out of the vehicle, they get deleted locally.  Trunk contents only exist for anyone mounted in the vehicle or anyone accessing that trunk.

**Comment by Mazo** [comment]
Fixed in #683

Note you won't be able to actually rearm from a favourite, that functionality appears to be missing currently. Buying ammo individually should work though.

**Comment by NickPSF** [comment]
Fixed awaiting check-in
