### ISSUE TITLE
Vehicles - ANT - Deployment checks missing

### ISSUE THREAD

**Issue by Dethdeath** [psforever/PSF-LoginServer#672]
If you deploy/undeploy an ANT quickly, you can end up with the following situations:

-ANT can be filled up while in an undeployed state at a warpgate (https://i.imgur.com/2G1lAuU.png)
-ANT can be driven around while filling up an NTU silo (https://i.imgur.com/yFL9YJt.png)
-ANT can appear deployed while not actually filling up the silo (https://i.imgur.com/smq95n3.png)

**Comment by Fate-JH** [comment]
It's too bad you can't just deploy anywhere.  The ANT with its flaps open is neat.
