### ISSUE TITLE
Disconnect - Desync - Persistence - Loadouts - Respawn - One or Multiple Players can be given a disconnect screen, and when reconnecting with persistence receive no items when pulling a Loadout, and do not receive a Release Corpse/Respawn button on Death

### ISSUE THREAD

**Issue by NickPSF** [psforever/PSF-LoginServer#719]
One or Multiple Players can be given a disconnect screen, and when reconnecting with persistence receive no items when pulling a Loadout, and do not receive a Release Corpse/Respawn button on Death.

**Comment by NickPSF** [comment]
We need a playtest to make sure this is still occurring

**Comment by NickPSF** [comment]
Still occurring. This happens in the void of Routers, but seemed more common when Routers were in play.

**Comment by ScrawnyRonnie** [comment]
This is still happening. I can only speak for myself, but I haven't had random disconnects recently (except in the below case), but had multiple happen yesterday.

While not exactly the same thing, _most_ of the time when a player reaches 49 minutes of in-game time (as shown on the play session stats HUD display) a disconnect happens. This seems to have started in the past month or two. Can't confirm how far back it started, but something about being logged in for that amount of time triggers this to happen.

**Comment by Fate-JH** [comment]
As this has segued into the 50-minute disconnect, and that shoiuld have been resolved, closing this isue assuming similar resolution was achieved.  Please make a new issue rather than reopening this one.
