### ISSUE TITLE
Zonewide - Desync - Crash - Specific zones can desync, causing most clients connected to become unfunctional, and when re-entering the zone, many things like Doors cease to function

### ISSUE THREAD

**Issue by NickPSF** [psforever/PSF-LoginServer#720]
Specific zones can desync, causing most clients connected to become unfunctional, and when re-entering the zone, many things like Doors cease to function.

**Comment by NickPSF** [comment]
We need a playtest to make sure this is still persisting

**Comment by NickPSF** [comment]
@Fate-JH This last occurred on 4/21/2021, shortly before a server restart to correct it.

**Comment by ScrawnyRonnie** [comment]
We had still experienced this issue in recent times (at least the first part where everyone would suddenly desync), but it hasn't happened in over a month when it used to happen every Sunday at least once. It stopped after this PR: https://github.com/psforever/PSF-LoginServer/pull/1024
I would go out on the limb and say this one is resolved, at least by what had been causing it. If it creeps up again we can make a new issue.
