### ISSUE TITLE
Persistence - The world is flipped Neutral when updating the server and/or restarting the server

### ISSUE THREAD

**Issue by NickPSF** [psforever/PSF-LoginServer#741]
The world is flipped Neutral when updating the server and/or restarting the server.

**Comment by Mazo** [comment]
This does happen occasionally in local dev too. It's intermittent. Maybe 1 in 10 times?

**Comment by Fate-JH** [comment]
Upon startup, `ResourceSilo`'s control agency checks whether it has any nanites to spend and, if not, it sends a `NtuDepleted()` message to the owning facility to make certain its internal state is correct.  It alternately sends `SuppliedWithNtu()` if there even one nanite in its coffer.  If the building is told it has no nanites, it will flag a power down state and refuse to `SetFaction(...)` on the building.  That is most likely why facilities with `ResourceSilo`s seem to fall neutral.  On top of this, the faction of a facility can not be set until it resolves two services, one from a `Receptionist` system and the other from `ServiceManager`.

The services need to be resolved by the building and the nanites need to be provided to the silo before the faction is acquired from the database.  I know that the `Startup()` message is currently dispatched to the silo in the same process that creates the `ResourceSilo` in the first place; I wrote it that way.  That makes it inevitable that the silos will update the buildings to "no power".  The code that sets the initial NTU of the silo is in `Zones` in its override of the `Zone.init(ActorContext)` method.  It would run afterwards and would race against the silos processing their startups, losing much more often than winning.  I don't know where in the code the database is queried about the state of the facility but window for working correctly is narrow.

That is what I believe is happening.

**Comment by Mazo** [comment]
Should be fixed in #751
