### ISSUE TITLE
Terminals - Advanced Hacking - Factions - Enemy terminals can get into a state where they appear hacked to the player, but cannot be used

### ISSUE THREAD

**Issue by NickPSF** [psforever/PSF-LoginServer#759]
Enemy terminals can get into a state where they appear hacked to the player, but cannot be used

**Comment by NickPSF** [comment]
![image](https://user-images.githubusercontent.com/59997100/114750298-73f34c80-9d19-11eb-97b9-57fad95f85f0.png)

**Comment by jgillich** [comment]
Another one in `LocalService`
![Screenshot from 2021-04-18 01-30-54](https://user-images.githubusercontent.com/347965/115129437-2101e980-9fe6-11eb-8018-cbec5f845a73.png)

**Comment by NickPSF** [comment]
Fixed awaiting check in
