### ISSUE TITLE
Softlock - Vehicles - Vehicle Spawning - Players can attempt to exit a Vehicle which is spawning, causing them to become softlocked

### ISSUE THREAD

**Issue by NickPSF** [psforever/PSF-LoginServer#776]
**Reproduction Steps:**

1. Navigate to a vehicle terminal
2. Acquire a Vehicle
3. Spam the 'G' button
4. Observe soft lock

**Video:** https://streamable.com/ex3ka3

Players can attempt to exit a Vehicle which is spawning, causing them to become softlocked.

**Current Result:** You can leave a vehicle that is spawning and cause a soft lock.
**Expected Result:** You shouldn't be allowed to exit your vehicle by pressing 'G' while in the vehicle spawn and autodrive process.

**Comment by Fate-JH** [comment]
If you rebind the control, you won't softlock by pressing 'G' during vehicle spawning anymore.  Problem solved.
