### ISSUE TITLE
Vehicles - Players randomly get stuck in Vehicles and Wall Turrets

### ISSUE THREAD

**Issue by NickPSF** [psforever/PSF-LoginServer#813]
Players randomly get stuck in Vehicles and Wall Turrets

**Comment by Fate-JH** [comment]
Looking for information on whether this issue still exists.

**Comment by ScrawnyRonnie** [comment]
Don't remember the last time (other than this - https://discord.com/channels/142775664192389121/142775664192389121/1043941519159210114) when either of these happened to someone. Linked message was a player known to manipulate things so until we see these bugs again I'd think it's good to close.

**Comment by Dethdeath** [comment]
I have seen the core beam message that they mention recently, but it was during a gating incident involving a geowarp. 
#440 is the only wall turret bug I'm currently aware of, I haven't seen anyone complain about them in recent months.
The vehicle stuff was probably fixed a long time ago.
