### ISSUE TITLE
Vehicle EMP Blast Kills Infantry

### ISSUE THREAD

**Issue by ScrawnyRonnie** [psforever/PSF-LoginServer#957]
Heavy transport vehicles kill infantry when the EMP blast is initiated. 
https://www.twitch.tv/videos/1183809393

They also highly damage vehicle armor.
![image](https://user-images.githubusercontent.com/73139382/138483874-1884ff80-fdf2-4f9d-ab4d-bef515110ca3.png)
The Fury was full armor before the blast.

**Comment by Fate-JH** [comment]
Should be solved as of PR #982.  Until merged, check the test server.
