### ISSUE TITLE
Seth, Solsar western spawn door doesn't open after being hacked

### ISSUE THREAD

**Issue by Dethdeath** [psforever/PSF-LoginServer#975]
Door lock might not be attached to anything?

**Comment by Fate-JH** [comment]
Related: #979

**Comment by Fate-JH** [comment]
Confirmed that spawn room door does indeed remain locked after door lock is hacked.

**Comment by Fate-JH** [comment]
According to the client, when this amenity in Seth is hacked, it refers to a lock 827.  IFFLock 827 is identified by the server as being owned by building `S_Amun_Tower` and thinks it is located at `x=4515.572 y=1906.3021 z=107.93733`.  Seth is centered much further to the North at `x=4566.0 y=6116.0 z=57.799004`.  The door to be opened is 594.

The zonemap for Searhus appears to be wrong.  The current 827 agrees with the incorrect server setup that it "should be" a `lock_small` at the listed coordinates and owned by the listed tower, yet it is physically located in Seth.

Which lock claimed this door as its own?

Assigning this to @Mazo or @jgillich, whichever of you feels more comfortable examining the raws of the zone objects.
