### ISSUE TITLE
Pele, Searhus courtyard door won't open

### ISSUE THREAD

**Issue by Dethdeath** [psforever/PSF-LoginServer#979]
https://user-images.githubusercontent.com/77748540/143003645-c4a7c0ff-d115-4d13-acc6-1e57362ca090.mp4

**Comment by Fate-JH** [comment]
The references for these doors are extracted directly from the game files and set up automatically based on that data.  It might be linked or positioned incorrectly. @Mazo

**Comment by Fate-JH** [comment]
Related #975

**Comment by Fate-JH** [comment]
Door at Pele, Searhus does not seem to display any further issues.
